### ISSUE TITLE
Support ReadtheDocs

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#105]
Based on discussion in #39, there is a concensus that we want to be supporting ReadtheDocs. I'm starting a new thread specifically for that action item.

Since NumFocus takes care of our Slack and Zoom costs, I am in discussions with them to see if we want to communicate with RTD as "Astropy" or as part of a larger contribution from NumFocus which could benefit more projects. I will update as we work this out.

**Comment by kelle** [comment]
We're gonna move forward with contributing as Astropy. I'll get in touch with RTD directly to figure out the arrangement that makes the most sense for us.

**Comment by pllim** [comment]
Please tell them that we really want to use their PR builder feature for `astropy`. My previous request for that was rejected because `astropy` is "too big and too active" but hopefully that is not a problem if we are a paying customer? Thanks!

**Comment by bsipocz** [comment]
there is also a short list of feature we would very much like for a very long time now, let's see maybe they are open to those being "paid for". 
(the most important is the disabling the github edit links that redirects to the stable branch. it shouldn't take time much for someone familiar with their JS)

**Comment by kelle** [comment]
Super helpful — anything else on the short list?

I can also cc you both on the email I send.

Kelle

--
Kelle Cruz, PhD
917.837.9748 — Hunter: x16486 — AMNH: x7930
Pronouns: she/her and they/them

**Comment by pllim** [comment]
Can't think of anything else for now. I think the issue that @bsipocz mentioned above is readthedocs/readthedocs.org#6297 (please correct me if I am wrong).

**Comment by bsipocz** [comment]
Yes, that's the issue. The other one I had in mind seems to be resolved very recently (being able to hide versions from dropdown, while they are still available with direct links). 

Another one, that I cannot find an issue for is the ability to disable indexing of old versions (we manually worked around that issue as were not able to add the robots files, but it's not a final, good solution). I suspect adding these custom configs on the project level might be a more significant feature request.

**Comment by bsipocz** [comment]
(but as @pllim said, the most important would be to be able to trigger builds from PRs)

**Comment by Cadair** [comment]
(As an aside, please do let me know how the discussions with RTD go and what kind of arrangement you end up with to enable PR builds etc, I would be potentially interested in replicating it for sunpy.)

**Comment by kelle** [comment]
email sent and cc'd @bsipocz and @pllim.

**Comment by kelle** [comment]
Finance committee approved support at the $600/year level. And Kelle used the PEX card to upgrade the astropy membership.

**Comment by kelle** [comment]
At our level, we can only make 10 projects ad-free. Which of the following 13 should be made ad-free? 
![Screen Shot 2020-06-26 at 11 41 45 AM](https://user-images.githubusercontent.com/1444249/85875389-1a2d9000-b7a2-11ea-9b08-5dc0551b9dae.png)

**Comment by bsipocz** [comment]
core and coordinated packages. Many of which is not on the list, but they should be.

That leaves two more slots, I would go for the template, and pyvo as for the latter the plan was to make it coordinated sometimes late last year.

**Comment by astrofrog** [comment]
Agree with @bsipocz that we should do core package + the 7 coordinated packages - we need to add astropy as a maintainer on all coordinated packages for them to all show up.

**Comment by kelle** [comment]
Do y'all need me to do anything else with this? Not sure who is can add astropy as a maintainer on the coordinated packages. Should we send an email to the maintainer's list with instructions?

**Comment by pllim** [comment]
FWIW -- As far as this issue is concerned, I think it can be closed when https://github.com/astropy/project/issues/105#issuecomment-650249275 is resolved. As for enabling it for those repos, they can be tracked as separate issues for the affected repos.
