### ISSUE TITLE
Process for requesting support for Diversity and Inclusion Activities

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-project#106]
It would be useful to have a process to fund Diversity and Inclusion activities with Astropy funding.   This should include the process for requesting funds, assess proposals, and a budget to support these proposals

**Comment by kelle** [comment]
This was completed via the #117 and [IDEA proposal process](finance/proposal-calls/2020-IDEA/InclusionDiversityEmpowerment.md).
