### ISSUE TITLE
SciPy 2020

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#111]
The SciPy conference is happening next week and is fully remote and quite a bargain! There is a combo of live sessions/tutorials and pre-recorded content for watching at your leisure. 

This conference is a great way to learn more about the python scientific stack via tutorials and talks. 
Also, it would be great for us as a community to support the Astro talks by Brigitta Sipocz (Astropy) and Monica Bobra (Sunpy), as well as the other astro-related content. The Astro Q&A is on Friday, July 10, 3:45-4:45 CDT and it would be nice to have as many of us there as possible.
Check out the schedule (times in US/Central):
https://www.scipy2020.scipy.org/schedule

Since registration is only $75 each, the Finance Committee has approved covering the registration fee for all interested maintainers.

Please email me directly or comment on this issue if you'd like a registration and I will try to buy them in bulk.

**Comment by kelle** [comment]
Registration closes Thurs July 3, so please let me know ASAP.

**Comment by astrojuanlu** [comment]
Hi! I had already registered when I saw this, not sure if reimbursement is a possibility.

**Comment by kelle** [comment]
@astrojuanlu: They will refund you and I'll include you in our bulk purchase. :)

**Comment by dhomeier** [comment]
Thanks Kelle, you can count me in as well!
I am not sure if I could participate in a sprint, if @mwcraig still gets to schedule one for the weekend, due to other appointments, but might still make it for the p.m. CDT.

**Comment by bsipocz** [comment]
I also haven't yet registered, so count me in the bulk one.
