### ISSUE TITLE
Fund core Project members with Moore grant

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#113]
Several emails have been sent around about this, but we don't have an issue here!

Goal: 
Fund core Project members (people in named roles [2]), that requested funding in the survey [3], and that can receive money
this year.

As of July 3, 2020, we have figured out the amount level (to be divided equally) and are almost ready to start getting contracts setup.

**Comment by crawfordsm** [comment]
Funding has been allocated for the core members for the FY20 year:

Income that we are currently distributing:
Core Dev: $125000
Developers: $30000
Developers (Spectroscopy): $22500
Total: $177500

Expenditures:
Matt Craig: 30000
Adam Ginsburg: 13263
Tom Robitaille: 5600
Astropy Operations Support Specialist: 28800
9 developers @11000 each: 99000
Total: 176663

**Comment by kelle** [comment]
I would like to keep this open until folks have actually gotten the funds. We can use this issue to discuss the process, any challenges people might face, or opinions they might have.

**Comment by jdswinbank** [comment]
The following scopes of work have been agreed in connection with this funding:

- [Jan Luis Cano](https://github.com/astropy/astropy-project/files/5464807/January.2020.Cano.SOW.pdf)
- [Lia Corrales](https://github.com/astropy/astropy-project/files/5464810/January.2020.Corrales.SOW.pdf)
- [Kelle Cruz](https://github.com/astropy/astropy-project/files/5464811/January.2020.Cruz.SOW.pdf)
- [Derek Homeier](https://github.com/astropy/astropy-project/files/5464812/January.2020.Homeier.SOW.pdf)
- [Stuart Littlefair](https://github.com/astropy/astropy-project/files/5464813/January.2020.Littlefair.SOW.pdf)
- [Stuart Mumford](https://github.com/astropy/astropy-project/files/5464814/January.2020.Mumford.SOW.pdf)
- [Adrian Price-Whelan](https://github.com/astropy/astropy-project/files/5464816/January.2020.Price-Whelan.SOW.pdf)
- [Thomas Robitaille](https://github.com/astropy/astropy-project/files/5464817/January.2020.Robitaille.SOW.pdf)
- [Ole Streicher](https://github.com/astropy/astropy-project/files/5464818/January.2020.Streicher.SOW.pdf)

**Comment by kelle** [comment]
These funds have been dispersed and contracts have ended.
