### ISSUE TITLE
Document who has login credentials to team accounts

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#115]
Following up on a great idea of @bsipocz.

We should make a document which records who has the logins to the various project team accounts and resources. 

All of the information is actually already stored centrally in a team account, so we really just need a list of the folks who have access to that. Just not sure the best place for that list. On the wiki somewhere? Other ideas?

**Comment by pllim** [comment]
I think for security reasons, that list should not be public.

**Comment by kelle** [comment]
The list of people who have access to the 1Password? We don't need to list the accounts, just the names of the people who can access the information. I don't think it's that big of a deal to list the names but maybe I'm missing something?

**Comment by pllim** [comment]
They might be targeted for phishing, social engineering, etc.

**Comment by kelle** [comment]
ok, so is there a good private place you think we should keep them? Maybe a private google doc that is just shared with all maintainers?

**Comment by hamogu** [comment]
And it might also not be wise to point out which password manager is used, because that makes pinshing easier. On the other hand, I hope that the key holders are well aware of these risks!

**Comment by eteq** [comment]
Good point here @hamogu - I tried to sanitize that information out of the thread by editing messages above to be more vague, although someone determined might be able to get it?  (Open to if anyone knows if there's a way to safely remove that info without removing the general exchange of ideas here)

**Comment by pllim** [comment]
> safely remove

Since you asked, absolutely the safest way that is possible on our side is to completely delete this issue. Maybe then open a new one that is sanitized? 🤷 

While I really appreciate that Astropy is trying very hard to be more transparent, credentials management should still be kept private IMHO.

**Comment by hamogu** [comment]
astropy,.team @ is also an account to check.

**Comment by hamogu** [comment]
Idea in the discussion: Perform an annual audit of all accounts, passwords, github permission etc. A good timing might be shortly after the annual Coco elections. Step 1 is to make a list of all accounts to be discussed...

**Comment by pllim** [comment]
Change all the passwords and see who complains. That will smoke them out. 😆

**Comment by kelle** [comment]
At the CoCo meeting, we reviewed who has access to what in our password manager. We strengthened the security of a couple of our most sensitive passwords but otherwise, it looked all good.

**Comment by pllim** [comment]
@kelle , does that mean this is resolved or is there something else?

**Comment by kelle** [comment]
Well, we've made progress by adding a "security audit" to our new CoCo workflow.

However, I am not sure we've addressed the original request which was to make more transparent who has access to what. I'll add that discussion to the agenda of our next CoCo meeting.

**Comment by pllim** [comment]
CoCo4 had done an audit. I think things in general looks good now. If we have missed anything, please open new issue(s). We have it on a checklist somewhere else to revisit again. Thank you!
