### ISSUE TITLE
Need a way to keep track of current contractors

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#116]
We've been bringing folks on "staff" with various different scopes of work and contract dates and we don't have a good way for keeping track. We'll also need a way to keep track of their payments, reports, and progress etc. Ideas are welcome for how to do this...all I can think of is a google sheet.

**Comment by pllim** [comment]
HR has some special software but I don't think it is free.

**Comment by kelle** [comment]
Do you know the name of the software?

**Comment by kelle** [comment]
We're gonna start with just using google sheets. This format is flexible enough to help us figure out what we actually need.

**Comment by kelle** [comment]
We are using the Invoices tab of a dedicated AstroPy-Moore google sheet in the NumFocus google drive and it's working quite well for our current scale.
