### ISSUE TITLE
 Dunlap Program: "Kicking Off Scientific Software Engineering Learning Resources with  the Astropy Learn Project"

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#132]
In collaboration with @mhvk , we are submitting a proposal to the Dunlap Seed Funding program (University of Toronto). The motivation behind the proposal is to hopefully start building a long-term relationship with Dunlap. For this initial proposal, we are hoping to expand the financial support for Learn Astropy and provide support for @jonathansick or comparable contractor for Astropy Learn.

**Comment by eteq** [comment]
The proposal has been submitted for the Oct 1 deadline.  Will update here when we've received a reply.

**Comment by kelle** [comment]
Submitted proposal can be viewed here: https://drive.google.com/file/d/1z-mV4YjkHyc6Xe645mO8kkjYlQC6rfgz/view?usp=sharing

**Comment by kelle** [comment]
This was approved. Woot!  up to CA$31,023 to use by Oct 10, 2022.
