### ISSUE TITLE
A series of project flowcharts

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#137]
I created the infrastructure one at #118 and many people rightly pointed out that other important parts of the project were missing. I did not mean for that one chart to be comprehensive. I propose, as a collective, the relevant experts create similar flowcharts for their area (see below). Then maybe we can have a flowchart of flowcharts to tie them all together. Having to open this issue also signifies how much the Astropy Project has grown since 2011! We should be proud of how far we have come since that first commit. 😃 

This list is also not comprehensive, so feel free to add:

* Infrastructure (#118)
* Release extravaganza (conda, PyPI, Debian, ...)
* Coordinated packages
* Website(s)
* Learn Astropy (tutorials, workshops, ...)
* Governance (CoCo, Ombudsperson, ...)
* People wrangling (?)

**Comment by pllim** [comment]
@embray suggested that "testing" in #118 should be expanded into its own thing.

**Comment by pllim** [comment]
@astrofrog suggested that maybe we don't need more flowcharts. Could look at alternative ways to present this info.

**Comment by kelle** [comment]
FWIW, I really like the flowchart idea. It doesn't need to be a proper flowchart, but the various packages/products which are related to each other. It definitely helps me see ALL THE THINGS and they are related. I could see flowcharts (or other similar type visual representations) being super helpful for funding proposals.

**Comment by embray** [comment]
I think the chart on #118 is already gives a sense of the scope of what we're dealing with.  I was convinced in the meeting that a visual diagram of CI systems would not be useful (instead I am attempting to gather answers to my specific questions about the current test infrastructure--I might attempt to then further synthesize a summary of the current situation to see if there's anything that can be simplified).

**Comment by pllim** [comment]
Might also be relevant: astropy/astropy.github.com#407

**Comment by pllim** [comment]
No one really did anything about this. I don't think it is going to happen.
