### ISSUE TITLE
Booth for AAS 237

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#140]
Following on from the NumFOCUS booth we helped organize for the previous AAS, for the 237th (virtual) AAS, we should have a booth again due to the success of the previous booth in facilitating both input from the astronomy community and the interchange of ideas that came from getting together a "many-project" booth like NumFOCUS.  This year we can use the Moore budget to support it, so we can think of it more as an "Astropy + NumFocus" booth.  

@eblur has volunteered to help coordinate again this year - thanks!

**Comment by eteq** [comment]
A thoughts/considerations that I wanted to add: The last one provided useful input from the "drop-bys" but we didn't have a clear mechanism to combine this input beyond word-of-mouth.  For this one we may want to have there be a spreadsheet (or even just a thread in this issue tracker?) to keep track of the items that people ask the booth staffers, as a way to sort of take a "snapshot" of the community's thoughts as it relates to the topics in the booth.

I also think  the "virtual" format is a bit untested, so we should regard this as a bit of an experiment, which I'm comfortable with but it will be very useful in the end also to hear whether we think it/s worse/better/same as the in-person event.

**Comment by kelle** [comment]
To be explicit, the Finance Committee has approved to pay for this booth + 4 webinars, to come out of the Moore travel budget.

**Comment by kelle** [comment]
Things we need to decide:  
- How we should be listed in our promotional materials and on your booth sign?
I vote "Astropy Project and NumFocus projects"

- one public email address
? not sure. 

- one twitter handle
I vote astropy_learn

- websites
We could list a lot...but maybe [astropy.org](astropy.org) and the [numfocus projects](https://numfocus.org/sponsored-projects) page.

- organization description (150 words)


This is due Oct 22 but let's try to get it all sorted it the next two weeks (by Oct 9).

**Comment by kelle** [comment]
Another thing that we haven't discussed is meeting registration. I assume that everyone who will be staffing the booth will be using other funds to cover their meeting registration. If we need to cover someone's meeting registration, we'll need to revisit the budget.

**Comment by hamogu** [comment]
To follow up on @eteq : We do have a problem that our community feedback to astropy is very biased towards heavy astropy users. A formal booth might give us the chance to take a snapshot of the broader astrophysics community. Why do people not use astropy? Is there certain functionality that's missing? What modules / packages are used most (personally, I suspect `io.fits`)? Are the docs not clear enough or are they too long? Do we need more tutorials? Or fewer? Is the installation too hard? Do people think they could contribute and if not, what's stopping them?

I know that even in an in-person booth you can't go through all these questions and more with every person walking up, but maybe a few can be discussed with some people. Any insight into these points would make the time and money spend on a booth worthwhile for the project.

I agree that a virtual booth is uncharted territory for everyone, but it's worth trying out.

**Comment by eblur** [comment]
These are all great ideas. Given this discussion, we are leaning towards the following answers for the booth registration:

How we should be listed in our promotional materials and on your booth sign?
Astropy and NumFocus sponsored projects

one public email address:
lia.astro@gmail.com

one twitter handle
astropy_learn

Websites:  
Learn.astropy.org
Astropy.org
numfocus.org

Second, we plan to keep a set of Google docs for the exhibit hall staffers. This will include:

* A log book for the booth -- _What did folks ask about, what types of conversations were had, etc._
* FAQ: For booth staffers -- _Questions people might ask that the folks staffing the booth should know: E.g., What is NumFocus?_ 
* An open list of questions for booth staffers to ask the visitors (informal survey) -- _Why do people not use astropy? Is there certain functionality that's missing? What modules / packages are used most (personally, I suspect io.fits)? Are the docs not clear enough or are they too long? Do we need more tutorials? Or fewer? Is the installation too hard? Do people think they could contribute and if not, what's stopping them?_

**Comment by eblur** [comment]
Here's the organization description that I put together

Organization description (150 words)

The Astropy Project is a community effort to develop a common core package for Astronomy in Python and foster an ecosystem of interoperable astronomy packages. In addition to providing core functionality for astronomical research with Python, there is a diverse assembly of Astropy affiliated packages for sub-field specific tasks, such as ccdproc, astroquery, and specutils. At this special virtual exhibit, we will host representatives from a variety of Astronomical Python research packages. We will also be available to answer questions about new initiatives sponsored by the Astropy project to support diversity and inclusion.

**Comment by kelle** [comment]
I have used the PEX card to reserve the booth.

**Comment by pllim** [comment]
Close?

**Comment by hamogu** [comment]
Before we close this, it would be good if the booth organizers could leave a few remarks / lessons learned / issues raised while talking to visitors etc.

**Comment by hamogu** [comment]
@eblur : Do you have any lessons learnt / feedback etc to post here?

**Comment by eblur** [comment]
Yes! We've put together a report on both the virtual exhibit hall booth traffic and feedback from the Astropy workshops.

https://docs.google.com/document/d/1uTIhWv-HqxdenJdbFa2vrskHUQwupS6gx31w9VH9800/edit?usp=sharing

**Comment by hamogu** [comment]
@eblur Thanks! That looks a lot more detailed than I thought we would get. I'll have to read it carefully, but the immediate consequence is that I can close this issue ;-)
