### ISSUE TITLE
ADASS2020 registration

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-project#141]
I wonder whether registration to ADASS2020 can be covered by the travel grant. I have a talk on astroquery focusing on our ongoing collaborations with various observatories and archives and to keep the ball rolling around ideas that covid messed up for this year.

Registration fee will double after the 30th of Sep, so a quick turnaround would be appreciated.

cc @astropy/finance-committee

**Comment by kelle** [comment]
I started an email thread with the Finance Committee and will push to get back to you by Tuesday so the Wed early registration deadline can be met.

**Comment by kelle** [comment]
If anyone else would like to attend ADASS as part of the Astropy Project, please let me know ASAP.

**Comment by kelle** [comment]
We've got Brigitta, Adrian, and Derek all registered. 🎉

**Comment by hamogu** [comment]
After the conference has passed, please provide a short summary (2-3 sentences) on your experience, work for astropy, and lessons learned.
If you gave a talk, presented work etc., please provide a link or copy and paste the abstract here.

This is both to keep a record for the future and make sure that the things you learned profit the entire project, but also to help us write the annual report for the Moore grant that funded this.

I'll leave this issue open until that's complete.

**Comment by bsipocz** [comment]
talk abstract:
```
astroquery: a community driven collaboration of data providers and data consumers


astroquery (http://astroquery.readthedocs.io) is an Astropy coordinated package and is already well embedded in and a key component of the astronomical Python ecosystem. astroquery arose from users’ desire to access databases from the Python command line in a scriptable fashion. Script-based data access provides the ability to make reproducible analysis and pipelines in which the data are retrieved and processed into scientifically relevant results with minimal user interaction, thus astroquery enables the creation of fully reproducible workflows from data acquisition through publication. The package currently consists of over 50 modules that provide direct access to the most commonly used databases, archives and services. While most of the modules share a similar API, they are meant to be used independently. 

astroquery has received significant code contributions from throughout the astronomical community, including both the user community and major archives. 
This talk will describe the philosophy, basic structure, and development model of the astroquery package as well a roadmap for future development. We aim to smooth the coordination between maintainers and the observatories even more and hope the talk will be a seed to further discussions.
```

**Comment by hamogu** [comment]
@adrn @dhomeier: Are you presenting anything? If so, please post title/abstract or link here.
@kelle: You have a talk, right? Please post title/abstract or link here.

**Comment by adrn** [comment]
> Are you presenting anything? If so, please post title/abstract or link here.
No

**Comment by hamogu** [comment]
@kelle I believe you are an invited speaker. I understand that your talk is still in the future, but I need at least a draft title for the Moore report.

**Comment by hamogu** [comment]
@kelle: The Moore annual report is due **tomorrow**. Since the Moore grant pays for your registration, I ask you to provide a draft title ASAP, either in this issue or as a comment in the Moore annual report document.

**Comment by kelle** [comment]
Actually, Moore didn’t pay for my registration. I did not pay a registration fee because I was invited. I’m not going to be able to work on my title/abstract by tomorrow.

**Comment by eteq** [comment]
Update here: we're thinking to keep this issue open until the conferences is over, so that @bsipocz, @adrn, @dhomeier , and @kelle can report anything of interest to the group in this issue for posterity.

**Comment by kelle** [comment]
my slides are available on [slideshare](https://www.slideshare.net/KelleCruz/astropy-project-update-for-adass). Feel free to ask me for source keynote.

**Comment by hamogu** [comment]
I'm going to close this issue now, but I encourage the attendees to still leave a comment with a a take-away point. Anything that you learned that the rest of astropy could profit from?
