### ISSUE TITLE
Setup core and coordinated packages with ReadtheDocs

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#147]
We are now paid supporters of ReadtheDocs (#105) and can make 10 projects ad-free. Ideally, those 10 projects should be core and coordinated packages. Right now, that is not the case (see screenshot below).

My understanding is that we need to add astropy as a maintainer on all coordinated packages for them to all show up. Could someone who understand this process better than I do send an email to the core-maintainers list to move this along?

![Screen Shot 2020-10-02 at 10 18 38 AM](https://user-images.githubusercontent.com/1444249/94935049-818e6680-049a-11eb-8010-0f8321311246.png)

**Comment by astrofrog** [comment]
The core package, astropy-healpix, astroquery, photutils, reproject, and specutils now all have astropy as a maintainer. I'm trying to track down who has access to regions, and we also need astropy as a maintainer on ccdproc (@mwcraig could you add the user ``astropy`` to the maintainers in the CCDProc RTD?)

**Comment by astrofrog** [comment]
@larrybradley - could you add ``astropy`` to the list of maintainers for astropy-regions since I see you have access? (https://readthedocs.org/projects/astropy-regions/)

**Comment by mwcraig** [comment]
@astrofrog -- I've added astropy as a maintainer to ccdproc

**Comment by astrofrog** [comment]
Thanks!

**Comment by larrybradley** [comment]
@astrofrog I've added `astropy` as a maintainer to `astropy-regions`.

**Comment by astrofrog** [comment]
Thanks! I think all coordinated packages should now have astropy as a maintainer. How do we make the projects ad-free?

**Comment by kelle** [comment]
login to readthedocs and adjust the settings. I can do it sometime this week or, Tom R. you can...I'm pretty sure you have the credentials.

**Comment by astrofrog** [comment]
I'm not sure I see the setting, will try again tomorrow

**Comment by pllim** [comment]
Re: ad-free -- Not sure which category you are, but it is documented at https://docs.readthedocs.io/en/stable/advertising/ethical-advertising.html#opting-out

**Comment by astrofrog** [comment]
The only option I see is to switch from paid to community ads but no way to remove ads completely:

<img width="390" alt="Screenshot 2020-10-05 at 23 42 49" src="https://user-images.githubusercontent.com/314716/95139500-7c643c80-0764-11eb-9aba-b847b6064bb3.png">

**Comment by pllim** [comment]
I clicked a few links and one of them brought me to their `.com` domain and required some sort of paid access. I wonder if that is how you do it with your paid account... Or maybe one of us can email RTD to ask about this...

**Comment by kelle** [comment]
I can take care of it tomorrow

**Comment by kelle** [comment]
Settings > Gold Membership > Select Projects.

Here's what I set it to:
![Screen Shot 2020-10-06 at 10 59 05 AM](https://user-images.githubusercontent.com/1444249/95219135-06db8900-07c3-11eb-9f20-b439240641be.png)
