### ISSUE TITLE
Give Madison admin access to astropy/astropy Travis CI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#149]
Please give @embray admin access to https://travis-ci.org/github/astropy/astropy so cancelling build is possible.

**Comment by astrofrog** [comment]
👍 - we should make a role and team to go with that, basically the devops role. I'll open a PR.

**Comment by eteq** [comment]
The DevOps role discussed in astropy/astropy.github.com#400 has been created and @embray added (among others) with astropy/astropy admin powers.  I am pretty sure that addresses this, so I'm closing.  But @embray can re-open if the access still isn't there!
