### ISSUE TITLE
Audit PyPI access for core package

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-project#163]
In light of automating the uploads to PyPI on the core package and the discussion in https://github.com/astropy/astropy/issues/10937 regarding trust in the PyPI authentication mechanism that an uploaded release is an "official" astropy release, should we consider restricting manual uploads to PyPI?

**Comment by pllim** [comment]
Yes.

**Comment by bsipocz** [comment]
Not exactly see why it would solve any trust issues, or it's not available any more of who did the upload?

**Comment by pllim** [comment]
We can also have a signing party for the few trusted release managers' PGP. Debian seems to do that (https://wiki.debian.org/Keysigning).

**Comment by bsipocz** [comment]
Yes, that could work as well. My only concern really is to limit the access to the signing key to those who have business with the releases and absolutely no one else, otherwise the trust in the signing is moot.

**Comment by pllim** [comment]
Yes, also need to set expiration dates and have a revocation certificate ready to go, just in case.

**Comment by pllim** [comment]
Can I go ahead and remove all the people except for @astrofrog and @saimn on the PyPI side? They are the current active release managers.

**Comment by hamogu** [comment]
Seems reasonable to me.
