### ISSUE TITLE
Pay for travis while we re-consider CI architecture

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#164]
Travis-CI has just announced the effective end of their free tier:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Based on that pricing structure, I've estimated our current usage for the Astropy Project as a whole:
* https://travis-ci.com/github/astropy?tab=insights indicates we used ~25k min in a month where ~half of the month was actually being counted.  But that was during the feature freeze, which is often a bit higher. And the previous week was 7k minutes, so ~25k min per month seems like the right ballpark.
* According to https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing linux is 10 credits per minute.
* I don't see a way to easily extract mac//windows minutes (which it says are 50 credits per min), but if I just assume the core is representative there's no mac build and ~1/7 windows, so average of 11.5 credits per min
* That totals 287500 credits per month. So at $15 per 25k credits, that's $172 per month

Note that's low-balling a bit, because we don't have a full month's worth of data.  So a long-term average might be more like $300 per month.

We need to re-evaluate all the CI infrastructure with this in mind, but as a tentative item we may want to try to make available ~1-2 mo to get headroom if possible.

**Comment by mwcraig** [comment]
FYI, Windows minutes are 20 credits/min, not 50 credits/min. Not a big deal.

**Comment by pllim** [comment]
https://github.com/search?l=&p=1&q=org%3Aastropy++filename%3A.travis.yml&ref=advsearch&type=Repositories

**Comment by eteq** [comment]
> FYI, Windows minutes are 20 credits/min, not 50 credits/min. Not a big deal.

Oops yes, typo on my part - my average assumed 20 not 50 so it should still be good within error bars :wink:

**Comment by pllim** [comment]
I think we can close this. The important ones are ported away from Travis CI and the few that are left are not active anyway.
