### ISSUE TITLE
Organize slides and talks for reuse

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#167]
There are lots of slidedecks floating around but we don't have a good way of organizing them for discoverability and reuse. Maybe we could just make a folder in this repo to upload both PDFs and source files?

**Comment by kelle** [comment]
We discussed this this morning at the Learn Telecon and realized Zenodo was a better home for talks than GitHub. I did some digging and re-discovered that we have an [Astropy Project community](https://zenodo.org/communities/astropy/?page=1&size=20) on Zenodo with APEs and code. I motion that we make a separate community for Astropy Project Talks and Presentations.  (We would move the one talk that's currently in there to the new community.) The nice thing about Zenodo is that you can upload both the source (PPT/KEY) and the rendered content (PDF).  

Any other ideas/suggestions/objections?  If you think making a new community is a good idea, please thumbs up this comment.  cc @bmorris @adrn @eteq

**Comment by adrn** [comment]
We discussed this at the CoCo meeting today and think this is a great idea! We think it makes most sense to just use the existing Astropy Project community on Zenodo, so we now just need to remind people to do this. We added a note to the CoCo "pending announcements" to include this in the next informational email we send. Should we close this issue? Or wait until we send that email?
