### ISSUE TITLE
DOC: Clarify what issues go to which repo

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#17]
At the time of writing, https://github.com/astropy has 76 repositories. It is getting confusing what issue should go where. There needs to be a page to clarify this somewhere (website?).

For example: What if I want to nominate/promote a new maintainer? Do I open PR over on team website repo? Or write something here?

**Comment by eteq** [comment]
I agree this is a good idea. I think this repo is a good spot for it, so someone interested in doing so should feel free to open a PR to this repo with a `where-to-make-your-issue.md` document or similar.  My one worry is about how to ensure it stays up to date, but that worry shouldn't get in the way of it getting done.

On @pllim's original question: that may need to be a topic for the governance re-factor, but until something new is proposed, I like the idea of making an issue here.  I'll add a label for that.

**Comment by pllim** [comment]
I think since then GitHub now let us move issues as needed. I don't think I want this anymore.
