### ISSUE TITLE
US English or UK English?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#173]
This topic has come up from time to time; once from a new contributor who wanted to help with writing doc. I think it would be nice if we can agree on one and stick with it for consistency's sake. I think https://docs.astropy.org/en/latest/development/style-guide.html was written with US English in mind, so there is already a precedence for US English?

Hopefully not too controversial...

**Comment by keflavich** [comment]
I'm in favor of US English for consistency's sake, but I'd also

**Comment by taldcroft** [comment]
This has already been decided and documented as "For consistency across Astropy materials, non-U.S. spelling will be edited to reflect American spelling preferences.".  (https://docs.astropy.org/en/latest/development/style-guide.html#spelling).

**Comment by pllim** [comment]
Okay, so US English it is. Thanks!

**Comment by bsipocz** [comment]
That being said, I would encourage everyone, in the name of welcoming and inclusive environment not to ask non native speakers to change their spelling. The decision was of the copy editor's preference rather than a community one, and the phrasing indicates that things may be edited away rather than being required.

**Comment by keflavich** [comment]
@bsipocz I take your point, though we do demand that level of conformity for actual code contributions (spelling differences in code are syntax errors, after all).

I suggest that we avoid making blanket demands of contributors along the lines of "please change all text to be US-English-conformant" - i.e., we should not ask contributors using UK-style English* to change their text.   But, we should allow reviewer edits done through suggestions (i.e., direct code-change suggestions to change the spelling) or later revisions to ensure a uniform style in the documentation.  Does that seem a reasonable policy approach?

* I am viewing this through a somewhat narrow lense of UK vs US English, i.e., most differences are colour-color and a few other subtle spelling differences along those lines.  I apologize for my ignorance if I'm describing the language differences incorrectly or I'm missing something that doesn't fit that categorization.

**Comment by pllim** [comment]
Yes, usually when this comes up, it is to address subtle differences. While I understand the need to be welcoming, I also like consistency, which makes it easier to `grep` or `sed` when bulk changes are needed across the repo.

Personally, I wouldn't say this is some "iron fist" policy, but rather when someone else which one is preferred, I would now say, "US English."

**Comment by bsipocz** [comment]
> I take your point, though we do demand that level of conformity for actual code contributions

If the code has a variable color, then of course it's not acceptable to start spelling it colour a few lines later. That's not language but as you said a syntax question. However, asking to change the spelling in a comment line doesn't make much sense, users will never see it, it's also not subject to `grep`, etc.
