### ISSUE TITLE
MNT: Change default branch name for future NEW repos in org

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#178]
https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-the-default-branch-name-for-repositories-in-your-organization

Only org admins can do this.

This is part of #151

**Comment by kelle** [comment]
I suspect Github has made this a new default. Can this be closed? @pllim ?

**Comment by pllim** [comment]
Yes. Thanks for the reminder!
