### ISSUE TITLE
Remove feature branches

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-project#187]
There are a couple of branches that should live in people's fork. Please remove them and work from forks instead, so those branches are not propagated into other people's forks and clones.
Thanks!

**Comment by kelle** [comment]
Hmmm, yes, thanks for bringing this to my attention. I'll work on it. I don't think I can just delete them because both of them are still in progress. I'll figure something out.

**Comment by kelle** [comment]
Ok, so I was able to close a stale PR and remove one of the branches. The other one is an active PR with my funding idea. I totally apologize for doing it this way, I didn't realize the potential repercussions. I'll definitely remember for the future. But now that it's done, I'm not sure how to easily undo it without closing and re-issuing the PR from my fork. Is that what you think I should do?

**Comment by pllim** [comment]
> Is that what you think I should do?

If the PR will be merged soon, I don't see the point of the extra steps of re-issuing from fork. But if it is going to stay open for a few more months, then perhaps; If you need help, feel free to ask. Thanks!
