### ISSUE TITLE
Maybe fund some template work?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#196]
I see some proposals to fund stuff and this is not my submission for the funding, but I thought it would be nice to have some money to get the template maintained, set clear scopes, etc. Currently there are 5 maintainers listed on the Team page but unfortunately still very little maintenance happening; in the order they appear on the page as of this writing: @larrybradley @Cadair @adrn @astrofrog @bsipocz 

During Astropy Coordination Meeting 2021, there seemed to be some confusion whether the template falls under "infrastructure" or "community." On the "infrastructure" side, there is actually not much overlap because the core and coordinated packages don't break when the template does not work, so it is not technically something that infrastructure team would care about as far as operations are concerned. I cannot speak for "community."

Related: #159 , https://github.com/astropy/package-template/issues

**Comment by eteq** [comment]
I think this is a great idea!

**Comment by hamogu** [comment]
We (the finance committee) have consulted with the package maintainers on this and even drafted a job ad to find someone to do that work. However, after the discussion it has become clear that new work is happening in https://packaging-guide.openastronomy.org/en/latest/index.html with the goal of creating something for the broader ecosystem, not just astropy users. In that light, just "ticking off issues" on the existing package does not seem like the best way to spend time. The openastronomy packaging guide is currently written by @astrofrog and @Cadair and some finding for work on this is available through a SunPy grant.

It is even possible that our astropy template might be deprecated in favor of the openastronomy packaging guide.
