### ISSUE TITLE
Fund core project members with Moore Grant 2021

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#199]
The process for allocating funds from the Moore grant is described in [Moore 2021](https://github.com/astropy/astropy-project/blob/master/finance/proposal-calls/Moore_2021.md).

Total funding of $ 200,000 are available in total in the period spring 2021 to spring 2022. Most of the money can be distributed to any area deemed important by the community. However, we do have specific budgets for work related to spectroscopy (22500 US $), mentoring contributors (15000 US $), and first contributor workshops (12000 US $).

Fifteen ideas were submitted. 

This issue should be updated with funding decisions and kept open until the funded projects are complete.

**Comment by eteq** [comment]
The funded PRs have now all been merged, and the details of funded proposals (and how the allocations were decided) are here:
https://docs.google.com/spreadsheets/d/17f5d4r3rRzEUXagIvzcSQkJknzGkuUeN4DRClwud08M/edit?usp=sharing

**Comment by dhomeier** [comment]
Details of completed work for #194 20210101-20210630:

- Finalised documentation and interface for `scipy.optimize` solvers in `astropy.cosmology.z_at_value` (astropy/#11080).
- Completed Humlíček implementation of astropy `Voigt1D` (astropy/#11177).
- Resolved inconsistencies in `WCSLIB` args for 7.4 update (astropy/#11260).
 - Fixed endianness check in `Table.to_pandas` exporter (astropy/#11288).
 - Fixed a FITS parser bug for RVKC headers (astropy/#11301).
 - Enable `WCSLIB` build in C99 mode (astropy/#11376).
 - Optimise padded input to `convolve_fft` for memory/speed (astropy/#11533).
 - Add tests for non-native-endian structured `dtype` (astropy/#11545).
 - Reduce units in return values of `Voigt1D`, `Lorentz1D` (astropy/#11397).
 - Add support for astropy 4.3 `PhysicalType` (specutils/#833)
 - Update `spectral_axis` tests to coordinate frame instances (specutils/#836)
 - Opened 2 astropy and 3 specutils issues.
 - Reviewed 32 astropy, 1 specutils and 1 lightkurve pull requests.
 - Worked on preparation and chairing of Coordination Meetings on the LOC.
 - Contributed to Roadmap and HPC working groups.
 - Participated in the Astropy Slack forum (fits, modeling, table, wcs, spectroscopy, timeseries) to answer questions and engage new users.
 - Participated in the Facebook Python users in [Astronomy](https://www.facebook.com/groups/astropython) and [Astrostatistics](https://www.facebook.com/groups/astro.r) groups to answer questions and engage new users.

**Comment by adrn** [comment]
Completed work for #190:

- Maintainer and lead infrastructure coordinator for Learn Astropy
    - Attended weekly Learn Astropy telecons
    - Continued oversight of work on major overhaul of Learn Astropy website. Work is being done by Jonathan Sick and reviewed by APW in the following repositories to prepare for the re-launch of Learn Astropy:
        - https://github.com/astropy/learn-astropy
        - https://github.com/astropy/learn-astropy-librarian/
    - Finalize new contributed tutorial content, including a major overhaul of the astropy.coordinates tutorials sequence: PR astropy/astropy-tutorials#460
- Several bug fix and enhancement pull requests to the Astropy core package:
    - astropy/astropy#11490
    - astropy/astropy#11628
    - astropy/astropy#11635
    - astropy/astropy#11686
- Reviewed 37 pull requests to the Astropy core package, as part of duties as maintainer of the astropy.coordinates and astropy.units subpackages
- Coordinate Astropy dev telecons and weekly astropy.coordinates co-working telecons
- Service:
    - Governance working group
    - Roadmap working group
    - Coordination meeting planning committee

**Comment by Cadair** [comment]
Completed work from myself and Tom R 2021-01-01 -- 2021-08-31:

* Coordination committee and project coordination meeting work.
* Governance implementation working group.
* Infrastructure working group attendance and related infrastructure development on Azure pipelines, other CI etc.

**Comment by lglattly** [comment]
This comment is regarding my updated availability for my 2021 funded project to copy edit the Astropy documentation and improve the style guide [#183](https://github.com/astropy/astropy-project/pull/183).

I am currently pursuing sudden opportunities in my fiction writing career and have less availability in 2021 than previously anticipated, so with approval from the Finance Committee, I am closing my project [#183](https://github.com/astropy/astropy-project/pull/183) so that the funding can be made available to other areas of the Astropy Project. I will keep the Finance Committee apprised of my availability, and may be able to complete some copy editing tasks upon request in 2022.

Thank you to the Finance Committee for this opportunity, and the flexibility and understanding with my changing situation!

**Comment by adrn** [comment]
2nd half of funding as requested in #190:

- Maintainer and lead infrastructure coordinator for Learn Astropy
    - Attended weekly Learn Astropy telecons
    - Continued oversight of work on major overhaul of Learn Astropy website. Work is being done by Jonathan Sick and reviewed by APW in the following repositories to prepare for the re-launch of Learn Astropy:
        - https://github.com/astropy/learn-astropy
        - https://github.com/astropy/learn-astropy-librarian/
    - Pull requests reviewed [here](https://github.com/astropy/learn-astropy/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me) and [here](https://github.com/astropy/learn-astropy-librarian/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3A%40me+)
- Bug fix and enhancement pull requests to the Astropy core package (full list available [here](https://github.com/astropy/astropy/pulls?q=is%3Apr+closed%3A%3E2021-06-01+author%3Aadrn+))
- Reviewed pull requests to the Astropy core package, as part of duties as maintainer of the astropy.coordinates and astropy.units subpackages (full list available [here](https://github.com/astropy/astropy/pulls?q=is%3Apr+reviewed-by%3A%40me+closed%3A%3E2021-06-01))
- Coordinating the writing of and infrastructure behind the next Astropy paper, to be submitted in Q1 2022 (“Astropy Paper 3”)
- Service:
    - Served on the Astropy Coordinating Committee 
    - Served on the Paper 3 Coordination Team

**Comment by dhomeier** [comment]
2nd half of funding as requested in #194:

- Contributed to Roadmap and HPC working groups.
- Participated in the _Astropy_ Slack forum and _OpenAstronomy_ Matrix room to answer questions and engage new users.
- Contributed to the core package and `specutils` in
 astropy/astropy#12034
 astropy/astropy#12241
 astropy/astropy#12295
 astropy/astropy#12302
 astropy/astropy#12367
 astropy/astropy#12505
 astropy/specutils#843
 astropy/specutils#850
- Reviewed 28 [core](https://github.com/astropy/astropy/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Adhomeier) and 3 [specutils](https://github.com/astropy/specutils/pulls?q=is%3Apr+is%3Aclosed+reviewed-by%3Adhomeier) pull requestsas `io.ascii` co-maintainer and ensuring coordination of spectroscopy packages over the 5.0 release.
- Accepted [Affiliated Package review editor](https://www.astropy.org/team#Affiliated_package_review_editor) position.
- Monitored the Facebook _Python users in Astronomy_ and _Astrostatistics_ groups to answer questions and engage new users.

**Comment by stargaser** [comment]
Bulk of funding for workshop support for #195. The contract will include AAS 240 in Pasadena and remaining funding will be used in support of that meeting (contract end date is 6/30/2022).

* Preparations for online AAS 237 workshop during Jan 2 through Jan 6, 2021. 15 hours
* Conducting four-hour Astropy workshop sessions at AAS 237 on 2021 Jan 7 and Jan 8, 8 hours total
* Preparations for online AAS 238 workshop on June 4th, 10 hours
* Conducting two 3-hour Astropy workshop sessions at AAS 238 on 2021 June 4th, 6 hours
* Attendance and workshop planning at Astropy Learn weekly meetings from Jan through August 2021
* Planning for the aborted AAS 239 Astropy workshop, 5 hours
* Service as core maintainer for astropy.constants module (low activity)

**Comment by jdswinbank** [comment]
The Finance Committee has been notified that the funds allocated to #191, #192, and #193 will not be claimed. We're returning those funds to our budget and will make them available through future funding rounds.

**Comment by keflavich** [comment]
Work for https://github.com/astropy/astropy-project/pull/174 funding me (Adam Ginsburg):

- Continued maintenance work on astroquery (steady-state effort; e.g. https://github.com/astropy/astroquery/pull/2136)
- Created new interfaces & deprecated old (e.g., https://github.com/astropy/astroquery/pull/2143)
- Ongoing communication with external teams (ESA, JPL, ALMA, NRAO, etc.)
- Serving as core maintainer of astropy.convolution (low activity)
- Serving as co-maintainer of regions (moderate activity; mostly reviewing)
- Integrating tutorials into astropy.learn (significant ongoing activity)

**Comment by mwcraig** [comment]
Work for #185 

+ Created conda packages for several relatively new (at the time) astropy affiliated packages and updated affiliated package feedstocks as needed.
+ Released a new minor version of ccdproc.
+ The CCD guide was used with a couple of classes of students to get additional feedback and refine the guide. 
+ The CCD guide backend was updated a couple of times because of new releases of jupyter-book.
+ Photometry efforts ended up focused on developing notebooks for interactive use, primarily in the [stellarphot repository](https://github.com/feder-observatory/stellarphot)

**Comment by aaryapatil** [comment]
Thank you for the summary @mwcraig! With that, Cycle 2 is complete.
