### ISSUE TITLE
GitLab backup plan

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#20]
Mirror GitHub code, issues, and pull requests, where possible, to GitLab. This is to reduce the risk of single point of failure in terms of project hosting.

As brought up during Astropy Coordination Meeting 2019.

**Comment by pllim** [comment]
GitLab is still nicer in a way that if something happens to GitHub, we can just switch to GitLab as primary.

**Comment by taldcroft** [comment]
I wonder about priority in a world where we are very developer-limited.  GitHub is now a very large company with a large number of paying corporate customers.  They have an excellent record for uptime and their business model depends critically on uptime and data integrity.  They will not suddenly shut off one day without significant advance notice, so if we find that GitHub is shutting down or becoming unacceptable to the project for other reasons then we can start worrying about migrating data and process.

Probably a more likely risk is a hack that results in data loss.  Maybe it's fair enough to think about backing up data from that perspective.  One presumes that GitHub has sufficient backups to mitigate risk of malicious activity, again this being core to their business model.

**Comment by astrofrog** [comment]
I'm not sure about specifically mirroring to GitLab, especially if that ends up being public and confusing users. I'd be ok with just doing regular backups to disk from time to time. I'm not too worried about GitHub's backup strategy, but I am concerned with e.g. GitHub shutting down API access to certain things in future and making it harder to get data out. So dumping all repos, issues, and comments to disk somewhere seems sensible to me.
