### ISSUE TITLE
Run Workshops at AAS 238

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#201]
Led by @stargaser and supported by the Learn folks, we are putting on two workshops at the (remote) AAS 238 meeting. The Finance Committee approved the facilitator registration costs associated with this activity. Multiple facilitator registrations are needed in order to monitor and interact with participants via the workshop Slack channel.

[Workshop planning document](https://docs.google.com/document/d/1JLPFvjwir0blMz3cRCWcHjVzMIPhlH1kyDAwHCmbdvc/edit)

[Workshop Materials](https://github.com/astropy/astropy-workshop)

I used the PEX card to pay for the conference registrations of Larry Bradley , Brett Morris, and Ricky O'Steen.

When the workshops are complete, a summary report of how they went should be posted in this issue.

**Comment by stargaser** [comment]
The AAS 238 workshops were conducted online on June 4th. The Astropy facilitators in the Zoom sessions and answering questions on the meeting Slack were Larry Bradley, Brett Morris, Ricky O'Steen, David Shupe, Nathaniel Starkman and Erik Tollerud. The AAS was strict about requiring all the facilitators to be registered.

The "Intro to Astropy" workshop had 59 registrants, and 40 participants joining on Zoom (not counting facilitators). The start time was 6am on the West Coast, which was too early for at least a few registrants. The technical sessions were presented by Nathaniel and Brett, including Brett's Intro to OOP and Nathaniel's new Cosmology tutorial.

The "Astronomical Research with Astropy" workshop had 59 registrants, and 39 participants joining on Zoom (not counting facilitators). The tutorial sessions were presented by David, Larry and Ricky, with Erik handling the Communities and Contributing at the end.

Lia Corrales set up pre-workshop and post-workshop surveys, which were sent to all the registrants via email and meeting Slack. Summarizing and reviewing the feedback is pending.

The AAS recorded the workshop sessions and they were made available to everyone registered for AAS 238 within two days.

**Comment by jdswinbank** [comment]
Thanks for the write-up @stargaser, (and apologies that it took so long to acknowledge it). I think we can now close this issue.
