### ISSUE TITLE
WoCCode activity

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#202]
The [WoCCode: Peer mentoring for the Women of Color coding community](https://github.com/astropy/astropy-project/blob/master/finance/proposal-calls/2020-IDEA/IDEA_2020_WoCCode.md) activity was funded as a 2020-IDEA proposal.

So far, we've paid for a guest speaker fees and for AAS 238 conference and workshops registration for two student participants. 

This issue can be used to provided further updates on the status of this activity.

**Comment by eblur** [comment]
Acknowledged. Regarding speaker fees, we should have a request submitted to NumFOCUS for the April 2021 speaker.

**Comment by kelle** [comment]
Update provided in #232.

**Comment by eblur** [comment]
University of Michigan was granted $5,611 as a sub-award from NumFOCUS on the Moore Foundation grant to Astropy.

That funding was used to pay for administrative support and WoCCode guest speaker honorariums through calendar year 2022.

We have a balance of $0 and we plan to close out the award on our side on the project end date of 06/30/2023.
