### ISSUE TITLE
Due October 2021 — Community Update

### ISSUE THREAD

**Issue by jdswinbank** [astropy/astropy-project#203]
Our last general community update was in [October of 2020](https://github.com/astropy/astropy-project/blob/master/finance/community-updates/2020-10.txt). However, since then we have sent regular mail to the community in support of the Phase 2 funding process.

At our [meeting of 2021-05-28](https://github.com/astropy/astropy-project/blob/master/finance/community-updates/2020-10.txt), we agreed that it would be appropriate to send another community update in “a couple of months”.

**Comment by hamogu** [comment]
We decided not postpone this until more has happened. We send out a lot of email about soliciting, reviewing and awarding funding, which kept the community informed, so, at this time, no separate update email is needed.

**Comment by jdswinbank** [comment]
We sent a community update in [December of 2021](https://groups.google.com/g/astropy-dev/c/WIY4Ml1ckz0), but forgot to close this.
