### ISSUE TITLE
Support project members to attend Scipy 2021

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#210]
The project supported the participation of several project members in the 2021 [Scipy conference](https://www.scipy2021.scipy.org/) and workshops: Kelle Cruz, Tinuade Adeleke, and Derek Homeier.  @kelle , Tinu, @dhomeier, could you please share something about your experience that might be relevant to the Astropy Project?

**Comment by jdswinbank** [comment]
Hey @kelle , Tiny, @dhomeier ...

> could you please share something about your experience that might be relevant to the Astropy Project?

Thanks!

**Comment by dhomeier** [comment]
Thought I had done this long ago, and I certainly should have, when memory was fresher!

Scipy 2021 was memorable as only the second virtual conference on scientific computing I attended, yet much more focused on the Python-based ecosystem Astropy exists in. It featured presentations of several lead contributors that shaped this system through decades, very noteworthy the keynote by Fernando Perez. This highlighted the specific challenges that open source projects face at this point of their evolution, having to adapt and upscale their model of a system built up by voluntary contributors to the requirements of a stable, connected computing environment.
The main sessions also provided a good preparation for the sprint sessions in the second part of the conference, one product of which has been a crucial bug fix for Astropy on HPC systems.

**Comment by kelle** [comment]
I attended several tutorials and talks and was impressed with large amount of remote participation. I came away with some ideas about how to improve facilitating remote tutorials for large audiences.

**Comment by hamogu** [comment]
@kelle For the benefit of the rest of Astropy: Can you give an example or two? Just bullet points is enough I think.

**Comment by kelle** [comment]
- Many co-facilitators are needed on discussion forum to help folks keep up
- The forum co-facilitators need a way to communicate with primary presenter so they can slow down and/or address problems being experienced by many people.

**Comment by jdswinbank** [comment]
Thanks Kelle & Derek! I think it's appropriate to close this issue down now.
