### ISSUE TITLE
Conference request: Invited speaker for AGU panel "Open Science in Action"

### ISSUE THREAD

**Issue by eblur** [astropy/astropy-project#211]
### Description

I was recently invited to be a panelist for a special session of the Fall AGU meeting, titled ["Open Science in Action"](https://www.agu.org/Fall-Meeting/Pages/Present/Abstracts/Open-Sessions#open). I accepted this invitation, with the plan to talk about Learn Astropy, WoCCode, and my role in HEACIT (a high energy working group).

To accept this invitation, I was required to pay for an AGU membership ($50) and an abstract submission fee ($70). I would like to be considered for reimbursement from any available Astropy travel funding.

## Title

The role of open source software in interpreting astronomical datasets

## Abstract

With upcoming ground-based and the next generation of space-based telescopes, the Astronomy research community is working with an ever increasing volume of observations, multidimensional data cubes, and sophisticated statistical techniques for getting the most out of a dataset. I will speak from my experience in the Astropy Project, a large open source software community that works to provide Python based research tools for the astronomy community. Under the Learn Astropy umbrella, we work to inform researchers at all career stages on Python workflows and best practices for contributing to open source software projects. I am also chair for the HEACIT (High Energy Astrophysics Codes, Interfaces and Tools) and can speak to the challenges of maximizing the analyses from current and future space based X-ray observatories. I can also speak about my experience founding "Women of Color Code", an online peer-mentoring program for women of color coders who are looking to contribute to open source software, a project supported by Moore Foundation Funding provided to the Astropy Project.

**Comment by eblur** [comment]
Hi folks, I submitted a reimbursement already for the abstract submission and membership fee. But now I need to register for the conference. It's $555 to attend remotely. The panel is on Dec 17. Can I get permission for reimbursement before going ahead?

@kelle this expense would be convenient to put on the P-card

**Comment by hamogu** [comment]
The finance committee discussed this request. We are a little concerned about the process; had we known initially that the total cost is almost 700 $, we would not have approved the full amount; it seems high for the relatively short (compared to the total length of the conference) contribution to a discussion panel. The finance committee approves to fund 50% of the total amount (555$ + 70$ + 50$) form our travel funding. If @eblur judges that presentation to be in the interest fo the WoCCode group, the remaining amount could be funded from the WoCCode budget.

@eblur : Please post your decision here and contact @kelle about using the P-card.

**Comment by eblur** [comment]
# Summary of the AGU Meeting special session: Open Data Science In Action

https://agu.confex.com/agu/fm21/meetingapp.cgi/Session/122142

**December 17, 2021 - 9:00 - 10:30 am EST**

## My presentation

**Slides:** https://docs.google.com/presentation/d/1bN-X87scVb5_lYo4mSHsI4R7urHAy5q_3V4xpu0KxSM/edit?usp=sharing

I only showed the first three slides. The others were there for personal reference.

I used the following notes for my talk

**Most popular tools in Astropy collaboration:**

- Jupyter notebooks -- We teach and publish a lot of material directly from jupyter notebooks. Astropy devs have created their own notebook reading / formatting modules in order to aid in this process. They are being used to build the Learn Astropy website.
- Numpy, Scipy, Matplotlib, and some baseline modules within the Astropy package: Units, Tables, IO (FITS), and NDData
- Usage -- Astropy mainly provides a baseline set of  Classes for users to build their own libraries. Very few choices are made for the user. We recognize that there is no one way to do things, and we support users developing their own methodology for doing so.

**Popular workflow**

- Import modules of interest
- Develop functions or other script utilizing the classes of interest (e.g., Spectrum1D)
- The functions or script are optimized and specific to the problem at hand
- E.g., if you are fitting a model you might use Astropy.modeling or your own custom Python code to produce a model image or spectrum. Then you will write your own code to evaluate the fit statistic (or use a pre-made statistic function) and run it through an optimizer (Scipy or Astropy). If it is a simple curve you are fitting, Astropy.modeling provides a lot of pre-set fitters.

**Why does it look this way?**

Astropy is meant to be general. Astronomy research is too broad to encompass in one major package. It merely provides fundamental tools

**How has this enabled better science?**

- Less time reinventing the wheel, especially for boring stuff (like input/output)
- Acknowledging that there are many valid ways to do the same thing, allow users to implement their own workflow
- This open source community (among others, such as yt) also helps sets standards for our community. Has been a leader in advocating for funding software and open source communities. Encouraging researchers to operate in an open source environment is helpful for reproducibility of results.
- The “Astropy Affiliated Packages” framework can help some people not reinvent the wheel and gain traction in the community.

**Approach to community, inclusive practices, encouraging development**

- One aspect of this is the Learn Astropy website
- We use jupyter notebooks, have infrastructure for ingesting notebooks and creating html pages from them, and have implemented a brand new search infrastructure for faster searches
- We now plan to grow the tutorial content significantly, as well as provide search infrastructure for tutorials that are provided outside of the Astropy collaboration

## Discussion Session

We had a 30 minute discussion with questions from the moderator. We discussed our own personal journeys to the open source community. We also talked about barriers to inclusion in open science communities. I talked about the Women of Color Code program, and how there is scholarly work demonstrating that strong identity formation (also framed as “confidence” among the group members) is essential for the persistence of people in marginalized groups in majority spaces. We also talked about micro-agressions and how we also need to do the work of addressing aspects of our community that discourage marginalized groups – it is not just a matter of encouraging people.

## Conclusions

**Link to summary document for the session:** https://bit.ly/open-science-agu21

**Some links to cool projects and initiatives that I learned about during the panel:**

- https://www.openscapes.org/approach/
- https://science.nasa.gov/open-science-overview
