### ISSUE TITLE
checklist for maintainers

### ISSUE THREAD

**Issue by crawfordsm** [astropy/astropy-project#212]
@eteq recently added me as a maintainer to help with the stats package and I was wondering if there was a checklist of things that should be confirmed before accepting a pull request?  

Although I do see this page:
http://docs.astropy.org/en/latest/development/workflow/maintainer_workflow.html
as well as another useful page (which I can't seem to find right now with a description of the code, testing, documentation, and change log)

I'd be happy to start putting a list together of things that should be checked and starting a pull request but obviously the people who have been doing this for awhile probably have a good idea what should be in the list.

cc: @astrofrog @embray

**Comment by pllim** [comment]
FWIW, the core lib has a checklist at https://github.com/astropy/astropy/blob/9d42e676a887eec99a0e08878b048e1a63dc3968/.github/workflows/open_actions.yml#L20 now. The Project does not enforce checklist for other stuff in the org but individual package maintainers are free to copy from the core lib.
