### ISSUE TITLE
Add astroquery contributors to the org

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-project#216]
This is a repeated begging that, please do add the astroquery contributors to the astropy github organization. At minimum, those working at archives contributing in the past 1-2 years need to be added. For names, see the git log. I have asked this many times already, explained the reasons, yet, here we are, basic maintenance chores cannot be carried out as apparently keeping the gates has still the utmost importance.

**Comment by mwcraig** [comment]
@bsipocz -- I think the short-term issue (getting some specific people into the org) has been fixed. Over the next couple of weeks some better solutions than running a script manually every few weeks or requiring that messages be sent by slack/email.

**Comment by mwcraig** [comment]
Forgot the question 🙄: can this be closed?

**Comment by eteq** [comment]
(the automated tool ion question is astropy/astropy-tools#170 )

**Comment by mwcraig** [comment]
Closing now that https://github.com/astropy/astropy-tools/pull/166 is in. A follow-up pull request will come by next week to turn this on. I believe the specific contributors were added to the org manually.
