### ISSUE TITLE
Consolidate Finance Committee Docs

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#224]
Currently we have some information about how the finance committee works in wiki pages and other information in markdown files. We have agreed to move the wiki info into markdown. So the action:

Move info from https://github.com/astropy/astropy-project/wiki/Financial-Management to https://github.com/astropy/astropy-project/tree/main/finance

**Comment by kelle** [comment]
add description of relative levels of privacy for each communication channel.

**Comment by eteq** [comment]
Once this is done, should also update https://github.com/astropy/astropy-project/blob/main/finance/finance-ctte-procedures.rst to remove reference to the wiki
