### ISSUE TITLE
Identify status of original "fiscal oversight team" for Astropy

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#23]
When the first agreement with NumFOCUS was signed, there was a "fiscal oversight team" that included the original coordinators (myself, @astrofrog, and @perrygreenfield) as well as James Turner (@jehturner).  (Possibly there were others, although I can't recall offhand and am not sure where to find the original document).

Since then, it seems NF's process has changed, as that team's role has basically been undertaken by the coordination committee (given that years passed between the oversight team's creation and any funding appearing).  But we should finalize exactly how this overlaps with the larger picture for NumFOCUS.

**Comment by jehturner** [comment]
As it happens, @taldcroft was also on the agreement -- so compared with the current committee I think it's just @kelle that wasn't on it and me and @perrygreenfield that are extra signatories. But I don't think any of that need affect the new finance committee much, as long as NumFocus is willing to work with them. My main concern is that the people making financial decisions may not be the same people responsible for them, in which case there needs to be some mechanism for keeping people in the loop. But clearly your new people are better placed than me to administer a fairly large grant in the US, so I don't want to get in their way :wink:.

I'll send you a copy of the agreement by email, as this probably isn't the place to keep legal documents(?).

**Comment by hamogu** [comment]
The last iteration of the agreement with NumFOCUS was signed by the current members of the Finance Committee. As I understand it, the process is that NumFOCUS will require new signatures every year and we'll have the finance committee (whoever is on it at the time) sign that. So, I think we can close this issue.
