### ISSUE TITLE
Add specreduce contributor to organization

### ISSUE THREAD

**Issue by ojustino** [astropy/astropy-project#236]
### Description

Hi, I'm working on [specreduce](https://github.com/astropy/specreduce/) through STScI and would like to be added to Astropy's GitHub organization.

**Comment by hamogu** [comment]
I sent an invitation. People can also just request to join the organization in the github webinterface and then we get an email that that needs approval (which we will do when we see it.)

**Comment by pllim** [comment]
> People can also just request to join the organization in the github webinterface

@hamogu , where is this documented?

**Comment by hamogu** [comment]
Not documented as far as I know. However, number of people did it that way so they must have found that button somewhere. I don't in fact know how to do that. However, I know that @mwcraig is looking into automating the process (e.g. invite anyone with more than X commits or something like that)
