### ISSUE TITLE
Dunlap Funding Opportunity

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#240]
Erik (@eteq) has identified a potential institutional partnership and funding opportunity between the Astropy Project, the Dunlap Institute, and the University of Toronto. This new proposal would build on the 1-year project started in 2021 (described in[ #132](https://github.com/astropy/astropy-project/issues/132)) and would potentially fund a postdoc and a graduate student based at University of Toronto (UT) and a consultant based in Canada. The funds would go entirely to the UT. The timeline would be for three years and would be renewable. The proposal is due April 1, 2022.

Because the intention of this proposal is to establish a partnership between the Dunlap Institute and the entire Astropy Project and not any particular individual, Erik brought the opportunity to the attention of the CoCo and the Finance Committee. The CoCo and the Finance Committee have evaluated the idea, provided feedback, and agree that it is an opportunity worth pursuing with Erik taking the lead. Other community members interested in helping out may reach out to Erik directly.

The CoCo has asked that the proposal be made available for review by the community at least two weeks prior to submission. Since the proposal suggests a likely integration between UT and other Astropy grant-funded activities (e.g. Moore mentorship program), the CoCo and Finance Committee should both approve the final proposal before it is submitted.

This issue can be used for community discussion and for updates on the proposal progress.

**Comment by eteq** [comment]
FYI, there is a start of a draft here: 
https://docs.google.com/document/d/1PIsS5l_eY12x7-IfkRGUO-MVcc4rFckGmGbUPThJ92Y/edit?usp=drivesdk

People are welcome to comment but I'll try to follow up here when there's a bit more completion.

**Comment by eteq** [comment]
This was submitted for the April 1, 2022 funding round.  PDF is here: https://drive.google.com/file/d/1ijNdODrxXhmPMDoUOttE_R42BeLE0lM7/view?usp=sharing
