### ISSUE TITLE
Archiver old repositories

### ISSUE THREAD

**Issue by ceb8** [astropy/astropy-project#243]
### Description
In the Astropy dev telecon of 1 March, we went through old repositories in the Astropy Org to see which ones can/should be archived. The list is in the [running notes](https://docs.google.com/document/d/15JSFh3OMF9Iz6ov3q_xxGO_BL8hRnuse4IMUrqEIvcg/edit?pli=1#bookmark=id.o0c9wn1r9fhf).

It requires someone with the correct permissions to actually do the archiving, so I am passing it along to you for that stage. All of the items in the to-archive section can be archived right away. The other section includes repositories that either need input from someone who was not there (noted in the list) or have other suggestions for handling.  The ones with additional suggestions need to be reviewed by the CoCo I think.

Also there is a suggestion at the end that the coco make a similar assessment on private repositories.

**Comment by hamogu** [comment]
I've archived those that were decided on in the telecon. I'll leave this issue open so I don't forget to check back on the notes for the others we still need to hear back about.

**Comment by pllim** [comment]
@hamogu , did you ever hear back about "the others"? Can we close this issue now in 2024? Thanks!

**Comment by hamogu** [comment]
No, I did not. We could put it on the list for the telecon again; even things we may have used 2 years again might be ready to be archived now.

**Comment by pllim** [comment]
Thanks for the quick response! Since you won't make it to the next telecon, do you have this list somewhere?

**Comment by dhomeier** [comment]
I've update the link above as well. And placing a reminder to myself to look into the
_Astropy-notebooks: Rename to io-ascii-benchmark-notebooks_ topic, as I may have last worked on these.

**Comment by pllim** [comment]
Here is the link to see the repos that we might target (oldest non-archived first, and may or may not show private repos depending on your team access): https://github.com/orgs/astropy/repositories?q=sort%3Aupdated-asc+archived%3Afalse

Here is an excerpt from 2022-03-01 notes that Jeff pointed out.

* Other:
  * FSA: move content into astropy-project repo?
  * Astropy-model-ideas: Move [astropy.modeling + mcmc notebook](https://github.com/astropy/astropy-model-ideas/blob/master/MCMCWithAstropyModels.ipynb) to astropy-tutorials?
  * Astrobot: ask Tom R.
  * Astropy-api: ask Tom R. about intention
  * Astropy-sandbox: ask Erik T. 
  * Astroquery-blog: Clara/Brigitta/Adam to discuss
  * Archived-documentation: Move to zenodo? Ask Tom R.
  * Astropython: Tom A. to ask finance committee for funding to keep site active
  * Astropy-docker: ask Tom R. and Larry
  * Wheel-forge: ask Tom R
  * Astropy-notebooks: Rename to io-ascii-benchmark-notebooks and change link in astropy documentation
  * Conda-channel-astropy: Ask Matt C. if this can be archived
* CoCo should look at private repositories

**Comment by pllim** [comment]
Here is updated list as of 2024-09-05:

* FSA: https://github.com/astropy/FSA/issues/2
* astropy-sandbox: https://github.com/astropy/astropy-sandbox/issues/2
* archived-documentation: https://github.com/astropy/archived-documentation/issues/2
* .github: https://github.com/astropy/.github/issues/3
* ci-helpers: https://github.com/astropy/ci-helpers/issues/468
* sphinx-example-index: https://github.com/astropy/sphinx-example-index/issues/5
* astropy-notebooks: https://github.com/astropy/astropy-notebooks/issues/5
* conda-channel-astropy: https://github.com/astropy/conda-channel-astropy/issues/187
* astropy-v5.0-paper: https://github.com/astropy/astropy-v5.0-paper/issues/131

**Comment by pllim** [comment]
OK done.
