### ISSUE TITLE
Create a new GitHub team for the Astropy release team

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#244]
Would it be possible to create a new GitHub team that corresponds to https://www.astropy.org/team.html#release_team - which would replace the core package release maintainers?

**Comment by eteq** [comment]
@astrofrog should definitely clarify, but my hunch is that the goal would be to expand the rights to *all* the coordinated packages, is that right?

So I would propose instead we take the existing team, rename it to match the roles, and update the membership to match the release team.

What is the right level of elevated permissions and which repos should it go to @astrofrog ?  Right now the existing team has admin on the core package and write on others. But this is old enough that it pre-dates the existence of the "Maintain" tier.  I'm guessing the right answer is that I should give at least some level of elevated permissions associated with *every* coordinated and infrastructure package, but is the right level "write", "maintain", or "admin"?

**Comment by astrofrog** [comment]
Renaming and updating makes sense. Not sure about permissions, maybe write is fine for now unless we need more?

**Comment by eteq** [comment]
Sounds good.  I will set the team to write for all coordinated and infrastructure packages, and feel free to ping me or another CoCo member if you want that upgraded.

I'll also make you, @astrofrog, an owner of the team, which I think makes it possible for you to add people later if need be.

**Comment by pllim** [comment]
![great powa](https://i.kym-cdn.com/entries/icons/facebook/000/017/572/uncleben.jpg)

**Comment by bsipocz** [comment]
We've been through this before, the write access is not enough to override branch protection measures and thus carry out the release procedure without inconvenient workarounds to go through the gates those with administrative power put up for those who actually do the work on the ground.

**Comment by eteq** [comment]
I added a bunch of repos (again, though, someone please check that those are the ones the release team actually wants...), and many do not have any branch protection turned on.

But I have no horse in this game.  If it's an impediment to the team, I will implement whatever the release team say is the right thing to do to making releases easier.  I just did exactly what @astrofrog asked above as the convener/now maintainer of the team.

**Comment by bsipocz** [comment]
> But I have no horse in this game.

It doesn't look like it.  In the current setup all on the coco can make a core release procedure, but those on the release team are not. Does it need to be Tom to point this out, as apparently I saying it for years is not enough?

**Comment by astrofrog** [comment]
Having thought about this more we definitely need admin access for the core package to carry out releases there, sorry for the oversight. I think we actually also need admin access on coordinated and infrastructure repos in order to be able to e.g. set tokens for PyPI and so on. So please disregard my previous comment about write access - admin access is the right level (basically the same as the devops team)

**Comment by pllim** [comment]
Then just join the devops team? 😆

**Comment by hamogu** [comment]
Addressed by #252
