### ISSUE TITLE
Fund participation in AAS 240

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#245]
The 240th meeting of the American Astronomical Society will be held in-person in Pasadena, CA in June 2022.

To further support the goal of increasing Astropy Project visibility at this meeting, we would like to make funding available to offset the travel costs of Project members’ attendance. If you are not fully funded by other sources to attend the meeting, please comment on this issue with a funding request and state the activities you plan to undertake that are beneficial to the Project. The funding request should include items and estimated costs. (For example, “approximately $1000 to cover two nights hotel and half of the airfare.”)

After the meeting, please comment the issue again with any results or take-aways that are useful for the Project as a whole. For example, “I spoke to folks from the AMAZING collaboration about functionality they need and possible new contributions. I got some feedback about the docs of the foobar package and opened issue ## describing the challenge in more detail.”

**Comment by rosteen** [comment]
@kelle Is this also usable to cover the cost of registering for the workshop, since it seems that even instructors are supposed to register and pay for that?

**Comment by kelle** [comment]
Yes. Please post explicit request and cost here.

**Comment by rosteen** [comment]
Great, thanks. I'm requesting $100 of support to pay for registration for the Astropy workshop on Sunday June 12, which I'll be helping run. I can email a copy of my receipt (I paid for this separately from the rest of the registration, which is covered by other funding) to whoever is relevant.

**Comment by kelle** [comment]
After travel is complete, please post reimbursement requests to https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new
