### ISSUE TITLE
Request more ReadtheDocs build limits

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#248]
Folks are encountering concurrency limits reached error messages when astropy repo is busy (e.g., a lot of people pushing to different PRs at the same time). We are going to request more concurrent builds as described here: https://docs.readthedocs.io/en/stable/builds.html

**Comment by kelle** [comment]
I sent an email and cc'd @pllim .

**Comment by kelle** [comment]
Success!  I will put the possibility of increasing our monthly contribution on the Finance Committee agenda. 

>  I've increased your limit to 8 concurrent builds. That was just for the `astropy` project, but let me know if there's other projects that are hitting this as well.
> 
> If you have the budget to increase your contribution to RTD, that is definitely something that we would appreciate, but only if it makes sense on your side. We are looking at formalizing this as an option for users who want to increase concurrency in the future, so I will take this as a vote for increasing the priority of that work.

**Comment by pllim** [comment]
Awesome! We can close this then?

**Comment by jdswinbank** [comment]
We discussed this in the Finance Committee, and we agreed that it would be appropriate to increase our donation to $100 per month. We think that's good value for the service we're receiving.
