### ISSUE TITLE
Fund participation in SciPy 2022

### ISSUE THREAD

**Issue by jdswinbank** [astropy/astropy-project#251]
SciPy 2022, the 21st annual Scientific Computing with Python conference, will be held in Austin, TX July 11-17, 2022.

To further support the goal of increasing Astropy Project visibility at this meeting, we would like to make funding available to offset the travel and other costs of Project members’ attendance. If you are not fully funded by other sources to attend the meeting, please comment on this issue with a funding request and state the activities you plan to undertake that are beneficial to the Project. The funding request should include items and estimated costs. (For example, “approximately $1000 to cover two nights hotel and half of the airfare.”)

After the meeting, please comment the issue again with any results or take-aways that are useful for the Project as a whole. For example, “I spoke to folks from the AMAZING collaboration about functionality they need and possible new contributions. I got some feedback about the docs of the foobar package and opened issue ## describing the challenge in more detail.”

**Comment by Cadair** [comment]
:wave: 

I would like to attend SciPy this year, but to the best of my knowledge the AURA/NSO travel policy still basically bans international travel. I would therefore like to ask Astropy to fund my travel for the main conference and the sprints, which would be approximately $1000 for flights and 6 nights of accommodation at $159 + tax ~= $1000. If the NSO travel policy changes before the trip, I would try and incorporate an NSO funded trip into this, which would at least reduce the airfare, even if they were unwilling to fund the conference. I don't have any other source of travel funding but could make up some shortfall personally if the requested amount is too much.

Aside from the general benefits of interacting with the wider scientific community, one of the main things I would be interested in collaborating with others about is the possibility of integrating xarray with WCS.

Thanks!

**Comment by eteq** [comment]
@Cadair - the astropy finance committee meeting met today and approved this request. You are welcome to either arrange your travel and request reimbursement after your travel (via the brand new Open Collective setup), or you can DM @kelle on Slack to arrange payment via the Astropy PEX card.

**Comment by dhomeier** [comment]
I am planning to join SciPy 2022 remotely for the main conference and part of the sprints. While the latter are free, I do not have specific funding related to the integration of Astropy in the Scientific Python ecosystem (e.g. the SPEC BOF) and am asking for funding for the 100 $ virtual participation fee.

**Comment by jdswinbank** [comment]
Hi @dhomeier  — approved by the Finance Committee.

**Comment by eteq** [comment]
Scipy 2022 is over, and the above folks all got approved, so I do not anticipate future funding requests, closing this issue!
