### ISSUE TITLE
Coordination meeting 2023

### ISSUE THREAD

**Issue by hamogu** [astropy/astropy-project#255]
At the Coordination meeting 2022 we decided:
- To have the 2023 coordination meeting in spring (May?) 
- A large majority favors a hybrid meeting 12 votes vs 6 votes for fully in-person
- location: Cambridge, MA, USA (MIT or CFA)

Potential SOC:

- (if in UK, which it's not this year):  Stuart Mumford (maybe) @Cadair 
- Pey Lian (yes) @pllim 
- Tom Aldcroft (yes, LOC) @taldcroft 
- Leo Singer (maybe, in particular if in Hawaii, which it's not this year) @lpsinger 
- Moritz Günther (yes, if at MIT/CfA) @hamogu 
- Wilfred Gee @wtgee (?)
- Matt Craig (willing, not chair) @mwcraig 

Topics to revisit (add further suggestions as comments to this issue):

- typing, see https://github.com/astropy/astropy/issues/14134#issuecomment-1341247450

**Comment by pllim** [comment]
Might also be good time to do v6.0 planning if not too late, @astropy/astropy-project-release-team ?

**Comment by pllim** [comment]
Maybe want to add roadmap again to this meeting too, @ceb8 ?

**Comment by ceb8** [comment]
Yes, definitely Roadmap should go on the agenda.  With a pre-meeting solicitation of items from the community.

**Comment by hamogu** [comment]
Notes on physical location and hybrid mode: At the 2022 coordination meeting we discussed different options for the location. Many contributors are located in North-East America, but to be inclusive to e.g. European contributors, it's not good to default to "US East Coast". After discussion and in light of the ongoing COVID thread and related restrictive travel policies for some institutions, the US North-East is one of the places with the best probability to actually get enough in-person participation to make a hybrid meeting (the preferred option) possible this time. Maybe the 2024 meeting can be in a different place again?

At the same time, the organizing committee should take steps to make a hybrid meeting work for others. Ideas are: 
- Put any discussion that might lead to important decisions into a dedicated 2h block in the morning that is easy to participate in on zoom.
- More ideas needed - please collect as comment to this thread.

**Comment by pllim** [comment]
From dev telecon today, we want to add this to potential topics to discuss during the meeting. cc @nstarman and @WilliamJamieson 

* APE 2 on deprecation policy -- we need to wrap it up and merge it, see https://github.com/astropy/astropy-APEs/pull/20

**Comment by pllim** [comment]
From Scipy 2022:

* https://github.com/astropy/astropy/issues/13460

**Comment by pllim** [comment]
There was a hybrid BOF at Scipy 2022. I'll leave a few notes here in case they are useful for our planning. There were some that I don't think apply to our meeting:

* For each hybrid session, have two moderators: One for on-site portion, one for virtual portion.
* Don't try to make virtual experience same as on-site; that is unrealistic. Instead, take advantage of unique opportunities that hybrid model presents.
* Enable and encourage virtual "hallway tracks".
* https://www.slido.com/

**Comment by pllim** [comment]
Sprint idea from Scipy 2022:

* https://github.com/astropy/astropy/issues/9017

**Comment by eteq** [comment]
At the NF Summit this year there was a session about "contributor experience lead" - the scope of this roles in other projects as somewhat variable, but it's something in a continuum between our concept of Community Engagement Coordinator and PR first-responders. Do we want to have a similar role in Astropy? And if so, how does it overlap with our existing roles?

**Comment by pllim** [comment]
Also this:

* https://github.com/astropy/astropy/issues/13910

**Comment by pllim** [comment]
Asked by @hamogu -- Do we want to select a priority theme for the next release(s)? (In the past we uses, e.g., "performance" as a theme.) Or not worth it?

Suggestions:
* Cloud-friendly
* Dask / xarray integration etc.
* Performance again

@eteq -- Some Cycle 3 funded projects for "cloud-friendly", but maybe for next release -- v6.1?

We can discuss unless CoCo decided to send another survey out and do it that way instead. cc @adrn

**Comment by pllim** [comment]
Possible future directions of the projects; high level goals we should work towards to as an organization to stay hip.

**Comment by pllim** [comment]
* https://github.com/astropy/astropy-sphinx-theme/issues/29

**Comment by hamogu** [comment]
Some ideas to integrate remote participants better into the meeting. Drawn from previous meetings I;ve attended and discussion in the Astronomers 4 Plenat Earth symposium.

- want to go beyond "listen in on zoom"
- https://tfom.org/ has a good list of resources
- We have one or two OWLs, which work pretty well in my experience for small groups (<20 or so) in person participants, not as well for larger groups.
- display remote participants on big monitor, so they are more visible and "on everyones mind"
- I've played with gathertown and https://hubs.mozilla.com/ or https://sci-an.com/. The latter two are more immersive, but have a  higher technical buy-in - yet this might be the crowd where it works.

**Comment by hamogu** [comment]
Results of [initial poll](https://docs.google.com/spreadsheets/d/1JCHLd7eknz5NfRWwSJYHlRRWBpJBAf2YJQ519Rn_lJc/edit?usp=sharing) indicate that about 50% of those interested are likely to attend remote with a a slight preference for a later in May over early April.

**Comment by pllim** [comment]
https://github.com/astropy/astropy-data/issues/131

**Comment by hamogu** [comment]
What do we want out of a User Survey? https://github.com/astropy/astropy-project/issues/11

**Comment by hamogu** [comment]
What direction will the core package take in the next few years? This is related to the discussion of the roadmap, but more specific to just the core package.
Future sub-packages for the core repository: In the past, there has been talk about merging some coordinated packages into the core, e.g. `regions`. That would make is more accessible (a lot more people install astropy itself then the coordinated or affiliated packages). What is the status of that? Are there any packages we want to include in the near future? Or do we promote those packages better? Or is it all good?

**Comment by pllim** [comment]
Finance Committee and/or budget updates.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1119008749

@taldcroft -- Is roadmap even used by Finance Committee wrt how to distribute funds? If not, what needs to change?

**Comment by nstarman** [comment]
> Future sub-packages for the core repository: In the past, there has been talk about merging some coordinated packages into the core, e.g. `regions`. That would make is more accessible (a lot more people install astropy itself then the coordinated or affiliated packages). What is the status of that? Are there any packages we want to include in the near future? Or do we promote those packages better? Or is it all good?

Something to discuss, but we could aggregate the docs for Astropy + coordinated packages using https://docs.readthedocs.io/en/stable/subprojects.html. This way the docs for coordinates packages are tightly integrated with Astropy and easily discoverable.

**Comment by pllim** [comment]
Update: I started a meeting page at https://github.com/astropy/astropy/wiki/MITMeeting2023 . Eventually, suggestions here will be narrowed down and, if selected, would appear in the Agenda section over there. When agenda is finalized, this issue will be closed. FYI.

**Comment by hamogu** [comment]
@aaryapatil @jdswinbank @keflavich @eteq : Question for the finance committee: Since the Astropy Coordination meeting is an astropy event, how do we want to handle requests for travel support for attendees? Is it easier for you to have people contact finance individually if they need support? Should be e.g. book hotel rooms through the PEX card directly? It would be great if the finance committee could discuss the process and leave instructions on https://github.com/astropy/astropy/wiki/MITMeeting2023

We will also request modest reimbursement for coffee etc., but don't have a budget request until we know the number of participants; it's likely going to be similar to the last in-person coordination meeting (there will be fewer in-person attendees than in 2019, but prices have gone up significantly since then).

**Comment by taldcroft** [comment]
Another potential topic: using GitHub Codespaces for astropy development, esp. for on-boarding new contributors.

**Comment by aaryapatil** [comment]
@hamogu The finance committee supports making full use of our travel funding for the coordination meeting! We have money available, so definitely should use it for travel support for attendees, reimbursement for coffee, and maybe even booking accommodation through the PEX card directly (we still need to discuss how the later would work in execution).

> Question for the finance committee: Since the Astropy Coordination meeting is an astropy event, how do we want to handle requests for travel support for attendees? Is it easier for you to have people contact finance individually if they need support? Should be e.g. book hotel rooms through the PEX card directly? It would be great if the finance committee could discuss the process and leave instructions on https://github.com/astropy/astropy/wiki/MITMeeting2023

I think travel support would be handled by NumFOCUS directly rather than the finance committee. We will provide a point of contact from them soon.

**Comment by kelle** [comment]
Please get in touch with Jim Weiss at NumFocus. The events team at NF should be able to help with lodging, catering, etc.

**Comment by taldcroft** [comment]
FYI, about codespaces, NumPy just announced this for numpy.

A GitHub codespace is now available for numpy/numpy.
Refer to the [GitHub documentation](https://docs.github.com/en/codespaces/getting-started/quickstart) for usage while we are finalizing a tutorial specific to numpy/numpy.
Please submit all your feedback on the NumPy codespace in this tracking issue: https://github.com/numpy/numpy/issues/23134.
I’d like to thank JP Ungaretti (@jungaretti), Sarah Kaiser (@crazy4pi314), Sebastian Berg (@seberg), Melissa Mendonça (@melissawm), and Craig Peters (@craiglpeters) for helping set it up and testing.

**Comment by pllim** [comment]
Re: Codespaces -- Is this what I am supposed to see on numpy? I see the same thing on astropy and we don't have anything set up.

![Screenshot 2023-01-31 115844](https://user-images.githubusercontent.com/2090236/215830666-0577b849-7465-4dab-aa57-e8fc8f3a37cc.jpg)

**Comment by seberg** [comment]
I think it is always there, NumPy just has a default config that should drop you into a usable state (i.e. conda installed all dependencies).  Unfortunately, right now it takes very long to load.  The setup itself is really pretty minimal though.

**Comment by wtgee** [comment]
> Re: Codespaces -- Is this what I am supposed to see on numpy? I see the same thing on astropy and we don't have anything set up.
> 
> 
> 
> ![Screenshot 2023-01-31 115844](https://user-images.githubusercontent.com/2090236/215830666-0577b849-7465-4dab-aa57-e8fc8f3a37cc.jpg)
> 
> 

Codespaces are tied to your personal GitHub account, so you can open a codespace on any repo within GitHub. I think the goal would be just to provide some default setup for the codespace so the intellisense works correctly. (We should also keep in mind GitHub now charges for space for these, so we shouldn't make it bloated or it limits how many codespaces people can have.)

However I do think we should discuss what the ultimate goal is. I find it difficult to do any "serious" work in the codespaces but think it's great for one-off quick edits. I imagine most people would use it for things like "Oh, here's a typo in the docstring, I'll just edit that right now." Most of the time when I use it on my repos I'm specifically skipping the feature-branch process.

I'd be great to see what numpy hopes to get out of it.

**Comment by pllim** [comment]
> here's a typo in the docstring

You don't need Codespaces to edit docstring though. You can bring your fork up to date with upstream, create a new branch on your fork, and edit that one line on GitHub all without any fanciness.

**Comment by taldcroft** [comment]
> You don't need Codespaces to edit docstring though.

You cannot test that your edits are correct prior to pushing. For anything but trivial changes, I will usually mess up sphinx.

**Comment by taldcroft** [comment]
> However I do think we should discuss what the ultimate goal is.

Great topic for the coordination meeting!! :smile:

**Comment by taldcroft** [comment]
For me, using CI to find sphinx errors is pretty frustrating since you may not get feedback for an hour.

**Comment by wtgee** [comment]
> Please get in touch with Jim Weiss at NumFocus. The events team at NF should be able to help with lodging, catering, etc. 

Hi @kelle, just to clarify, the individuals who wanting funding should get in touch with Jim or should the SOC?

**Comment by weaverba137** [comment]
Spectroscopy, please.

**Comment by pllim** [comment]
> Spectroscopy, please.

@weaverba137 , can you please clarify? What are the topics on spectroscopy that you wish to discuss?

**Comment by weaverba137** [comment]
I would like to hear reports from the spectroscopy development teams, so that I can report back to my institution, which is very interested in this topic.

But mainly, I was surprised that no one had thought to mention it until just now.

**Comment by weaverba137** [comment]
An additional spectroscopy topic: Is [APE 13](https://github.com/astropy/astropy-APEs/blob/main/APE13.rst) still considered current? It is now 5 years old. If it is not current, is there a current replacement? I want to be able to point people from outside the Astropy community to that document or its equivalent.

**Comment by pllim** [comment]
New suggestion: Unconference topic about governance of contracts.

**Comment by aaryapatil** [comment]
@ wtgee and others wondering how the funding process would work: We will approve all travel funding, without prior approval, which is for registered participants of the meeting and is compliant with the guidance published at https://github.com/astropy/astropy-project/blob/main/finance/process/request-funding.md#prior-to-travel (but without needing to submit a travel request)

**Comment by pllim** [comment]
Tentatively, we can discussed the proposed APE 21 if it is still not accepted by the meeting:

* https://github.com/astropy/astropy-APEs/pull/82

**Comment by kelle** [comment]
Topic: How can we better support and encourage Project member's attendance and participation in conferences like ADASS.

**Comment by wtgee** [comment]
It would be good to have a conversation about how we can support the rest of the planet that is not in the USA or Europe, in particular large markets like India, China, Japan, etc.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1452502711

@wtgee , do you have something more concrete in mind? This came up a long, long time ago, but no one knew how to get around geopolitical limitations.

**Comment by wtgee** [comment]
> Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1452502711
> 
> 
> 
> @wtgee , do you have something more concrete in mind? This came up a long, long time ago, but no one knew how to get around geopolitical limitations.

Honestly I'm not too sure what concrete actions there could be, I just get the feeling that there are probably a lot of people (especially students) that we could support/utilize better. I guess I'm imagining a discussion but admittedly don't have a ton to offer in that conversation. 

We talked about having the coordination meeting in Hawaii as a way to potentially get more people from the Asian-Pacific involved so maybe we could just consider that for 2024.

Maybe a simple thing to do would be to make some kind of poll that directly asks the question and try to get people in those countries to fill it out. 🤷

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1453943584

Thanks for the ideas, @wtgee . Let me bring them back to the next CoCo tag-up and discuss there as well, since SOC and CoCo do overlap and I think CoCo meets first. 😸

**Comment by dhomeier** [comment]
> We talked about having the coordination meeting in Hawaii as a way to potentially get more people from the Asian-Pacific involved so maybe we could just consider that for 2024.

I think we did discuss scheduling the time slots for the last (virtual-only) coordination meeting such as to optimise them for as many time zones as possible, but at the time had virtually no feedback from outside the main European and American zones. But we should certainly update this regularly, to make it clear that other segments of the globe will be considered as well. I believe the last remote ADASS had some slots accommodating East Asian/Australian participants, and I guess there will be more on location in South America or Asia every 3-5 years.

**Comment by dhomeier** [comment]
Other note to self, but also to others interested: more active participation in https://www.euroscipy.org/2023/program.html . That does not really get out of the North-Atlantic bubble, but I still think it would be nice to have better presence there.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1457224461

@weaverba137 , there is currently no auto-update available. I don't think this warrants a coordination meeting slot unless you have some specific ideas you want to hack on?

**Comment by weaverba137** [comment]
I was thinking about it in terms of affiliated packages, and I'm pretty sure that is a topic. If you'd prefer, I could bring it up under that topic.

**Comment by weaverba137** [comment]
How about this: Is there a way to know what upstream dependencies Astropy currently supports (equivalently: is being tested against), independently of tracking down the testing configuration files and reading those? If that *did* exist, one could conceive of packaging it in *e.g.* JSON or YAML format, then dropping those versions into templates of *e.g.* `setup.cfg`, `tox.ini`, `.readthedocs.yml`, `ci_workflows.yml`, etc.

And that's maybe an issue to open on `package-template`, etc., rather than a meeting topic.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/255#issuecomment-1458452831

@weaverba137 , I opened issue at https://github.com/OpenAstronomy/packaging-guide/issues/35

**Comment by pllim** [comment]
Any extra stuff, we can play by ear next week. Thanks, all!

https://github.com/astropy/astropy/wiki/MITMeeting2023
