### ISSUE TITLE
Add @astrofrog to archived-documentation

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#258]
The repository https://github.com/astropy/archived-documentation is used by a branch of the core package as a submodule:

https://github.com/astropy/astropy/tree/older-docs-archive/docs

I would like to be able to administrate this repo to edit the README and update the description to explain how the repo is used, and to make sure we don't get rid of it.

**Comment by hamogu** [comment]
I added you with admin role to that repro.
