### ISSUE TITLE
Add Leo Singer as admin of astropy-healpix on PyPI

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#259]
### Description

From @lpsinger , "Does anyone have the ability to make me a co-owner of the `astropy-healpix` package on PyPI? I've been pinging @cdeil and @astrofrog about it"

**Comment by lpsinger** [comment]
Blocking astropy/astropy-healpix#171.

**Comment by cdeil** [comment]
@lpsinger - I added you just now, you should have an invite. Once it works and you've added the relevant people, please remove me, as I left astronomy quite a while ago and won't have time to contribute. Thanks!

**Comment by lpsinger** [comment]
@cdeil, I removed you. Sorry to see you go.
