### ISSUE TITLE
Give Matteo Bachetti correct permissions as astropy core maintainer

### ISSUE THREAD

**Issue by WilliamJamieson** [astropy/astropy-project#261]
### Description
@matteobachetti is listed as a core maintainer for `astropy.io.misc` on the [astropy team page](https://www.astropy.org/team.html), and has requested to be added to the CODEOWNERS file being introduced by astropy/astropy#13241. However, GitHub is detecting an error which appears to be related to his permissions: https://github.com/astropy/astropy/pull/13241/files.

Could someone make sure @matteobachetti has the correct core-maintainer privileges for astropy?

**Comment by hamogu** [comment]
@matteobachetti should have write permission and it seems we've overlooked this before - so, I'm glad we are doing this and find these inconsistencies.

@matteobachetti : You should have gotten an email from github to join the astropy organization. I can't give you write permissions until you accept that. Once you do, this problem should be solved.

**Comment by matteobachetti** [comment]
Thanks @hamogu!

**Comment by pllim** [comment]
So, is this resolved? Thanks, all!

**Comment by WilliamJamieson** [comment]
astropy/astropy#13241 now shows no errors. So it looks all fixed
