### ISSUE TITLE
Astropy Paper 3 page charges

### ISSUE THREAD

**Issue by adrn** [astropy/astropy-project#263]
### Description

The [paper](https://github.com/astropy/astropy-v5.0-paper) has been accepted and passed to production! We will need to pay the page charges soon (estimated around $2500). How should we proceed with that?

**Comment by kelle** [comment]
When the time comes, I can provide AAS/IoP with a credit card number.

**Comment by pllim** [comment]
Wow, is publishing science paper usually that expensive? Time for us to sell some NFTs.

**Comment by eteq** [comment]
@pllim - yeah, that's pretty normal.  If anything a bit on the low side!

**Comment by eteq** [comment]
The finance committee approved this on July 25. Will be in touch with @adrn to work out exact details.
