### ISSUE TITLE
Project Calendar: Post on Scientific Python?

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#287]
@astrojuanlu went to the Scientific Python Ecosystem Coordination BOF at Scipy 2022. He suggested that perhaps we could post our project calendar on https://scientific-python.org/calendars/ .  In fact, he is adding `poliastro` calendar there:

* https://github.com/scientific-python/scientific-python.org/pull/263

cc @astropy/coordinators

**Comment by kelle** [comment]
On my list!

**Comment by pllim** [comment]
Didn't happen.
