### ISSUE TITLE
Please add Drew Leonard to the org / astropy-mentoring

### ISSUE THREAD

**Issue by Cadair** [astropy/astropy-project#290]
### Description

@solardrew is going to help out with the mentoring project going forward, please can you add him to the org.

**Comment by eteq** [comment]
I just added @SolarDrew to the @astropy/astropy-mentoring team which should give access to the astropy-mentoring repo. (@SolarDrew will need to accept before it's active though)

**Comment by SolarDrew** [comment]
Many thanks, @eteq  :)

**Comment by eteq** [comment]
Hah, that was faster than I could find another medium of communication @solardrew!
