### ISSUE TITLE
Create new astropy-figure-tests repository

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#297]
As part of https://github.com/astropy/astropy/pull/13596 I am going to need a new repository in the astropy organization called 'astropy-figure-tests' with admin permissions for the testing infrastructure team. Since this is going to be a repository that we automatically push to, it makes sense to keep separate from astropy-data, in case of any issues.

**Comment by hamogu** [comment]
done.

**Comment by astrofrog** [comment]
Thanks!
