### ISSUE TITLE
Fund travel to AAS 241 

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#305]
The 241st meeting of the American Astronomical Society will be held in-person in Seattle, WA, USA in Jan 2023.

To further support the goal of increasing Astropy Project visibility at this meeting, we would like to make funding available to offset the travel costs of Project members’ attendance. If you are not fully funded by other sources to attend the meeting, please comment on this issue with a funding request and state the activities you plan to undertake that are beneficial to the Project. The funding request should include items and estimated costs. (For example, “approximately $1000 to cover two nights hotel and half of the airfare.”)

After the meeting, please comment the issue again with any results or take-aways that are useful for the Project as a whole. For example, “I spoke to folks from the AMAZING collaboration about functionality they need and possible new contributions. I got some feedback about the docs of the foobar package and opened issue ## describing the challenge in more detail.”

**Comment by nstarman** [comment]
Hi! @kelle. Sorry for the 11th hour request. I'm presenting tomorrow (remotely) and I was hoping Astropy would cover the 1-day remote attendance fee for presenting. Is this the right thread for this? Thanks!

**Comment by kelle** [comment]
Let's take this convo to Slack. We'll post the outcome here.

**Comment by nstarman** [comment]
Outcome: I'm presenting as part of the astropy workshop and I'll submit to OC. Thanks @kelle
