### ISSUE TITLE
Funding PASEA

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#308]
This issue is for tracking the cycle 3 project "The Pan-African School for Emerging Astronomers 2022". FR is in #282, and details of the proposal are at https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/pasea.md . Budget is $11550, funded from the Moore grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-moore-8435))

**Comment by eteq** [comment]
The expenses for this project are reimbursements for travel and conference work, so @aaryapatil et al, you should submit reimbursements requests to the [moore project on OpenCollective](https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new).

**Comment by aaryapatil** [comment]
@eteq The following is a short summary of our work:

We organized [PASEA 2022](https://www.paseaafrica.org/pasea-2022) from October 5th - 15th in Livingstone, Zambia. We had students from ~13 different countries in Africa. There were a total of ~40 students out of which ~15 were in the postgraduate stream. 

Heidi White and I were responsible for running the first two days of the postgraduate stream that focused on astronomical data analysis using Python/Astropy. Our materials are hosted at https://github.com/heidiawhite/pasea2022. 

We went through a series of Python notebooks in the first two days that covered topics such as

1. Basics of Python
2. Plotting publication quality figures
3. Handling FITS files
4. Linear and Logistic Regression
5. Introduction to Neural Networks

We covered these topics using data from Kepler, SDSS, and LCO.

The second day also included a **Contributing to Astropy** workshop in which we completed an *[Introduction to GitHub](https://github.com/skills/introduction-to-github)* course and learned about the guidelines to contribute to the Astropy project. We opened the [Pull Request 13823](https://github.com/astropy/astropy/pull/13823) in Astropy as a result of this workshop.

Let me know if you need any other details.

**Comment by pllim** [comment]
https://github.com/astropy/astropy/pull/13823 never got out of draft status. Do you know if they plan to come back and wrap it up?

**Comment by aaryapatil** [comment]
I'll get back to them and complete it soon!

**Comment by eteq** [comment]
We've approved 3 sets of expenses for this project, and the remaining budget is US$97.33 - which by the way, @aaryapatil , is an *execellent* job of budget planning! :clap: :clap: :clap: 

Given that, am I right that we can consider this project done, @aaryapatil ?  If you agree we can go ahead and close this issue.

**Comment by aaryapatil** [comment]
@eteq I think there is one more _small_ expense (100-200 USD) for internet expenses that needs to be claimed. @heidiawhite will claim that amount soon.

**Comment by heidiawhite** [comment]
Hi @eteq - yes, @aaryapatil is correct and there is one final expense for internet services that I will be claiming this week. Thanks for the reminder!
