### ISSUE TITLE
annual prizes and/or awards

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#31]
We should have prizes and/or awards **every year**. They can be different for every person depending on their effort level. E.g., a new hoodie for most folks but customized things for ~5 folks reaching some kind of milestone (e.g., 10 year contributor, most valuable player). 

(We could do this as soon as Python in Astro in the Spring.) 

@taldcroft: Please put some example milestones and prizes you think would be good.

**Comment by pllim** [comment]
What about Pun Contest? :joy_cat:

**Comment by pllim** [comment]
I had seen this being tried out at other org and didn't turn out so well (question of fairness, etc). Better not.
