### ISSUE TITLE
Cycle 3 Funding: Hire a community manager

### ISSUE THREAD

**Issue by jdswinbank** [astropy/astropy-project#310]
This issue captures execution of the Cycle 3 project “Hire a community manager” (#284). The full text of the proposal is available [here](https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/community-manager.md).

This project was funded to the level of $48,000, funded from the Moore grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-moore-8435))

**Comment by jdswinbank** [comment]
The Moore funding currently has $58.5k unallocated in the “Consultant - Project Administrator/Manager” line item. I propose we can use that for this position. Finance ctte members (@kelle , @aaryapatil , @eteq ), can I get a 👍 if you're happy with that?

**Comment by pllim** [comment]
Might be a good resource for this hire: https://contributor-experience.org/

**Comment by hamogu** [comment]
I want to point out that there is significant overlap in the Code or Conduct portion of this plan with other activities that we already discussed at the Coordination meeting and with NumFOCUS (through a ChanZuckerberg grant) sponsoered activities in https://contributor-experience.org/. We need to keep an eye on wasting our efforts if different groups in Astropy develop different CoC proposals independently.

**Comment by kelle** [comment]
Yes, absolutely. These existing efforts were discussed at our kick-off meeting. Thanks for making sure though!

**Comment by kelle** [comment]
This work was completed.
