### ISSUE TITLE
Cycle 3 funding: Maintenance on astroquery, etc.

### ISSUE THREAD

**Issue by aaryapatil** [astropy/astropy-project#315]
This issue captures execution of the Cycle 3 project “Maintenance on astroquery, etc.” (https://github.com/astropy/astropy-project/pull/271). The full text of the proposal is available [here](https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/ginsburg.md).

This project was funded to the level of $14,700 , funded from the NASA grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-nasa)).

**Comment by aaryapatil** [comment]
Hi @keflavich, Apologies for the delay. Could you please fill in the Rocket registration form at https://numfocus.typeform.com/to/umyusM ? This is necessary even if you've registered previously. Please feel free to use “dummy” data for questions that don't apply to your situation, and ping me directly if you hit problems.

**Comment by keflavich** [comment]
@aaryapatil Done!

**Comment by keflavich** [comment]
@aaryapatil While I filled out the form, including a w-9, this is unfortunately not the right way for me to get paid.  I will need to be paid through a subaward through my university, which is how I received funding in previous cycles.

**Comment by aaryapatil** [comment]
@keflavich Apologies for the mixup. Yes, you did not need to fill the form and will be paid through your university. I somehow got confused about the payment process (I am still learning, sorry).

**Comment by keflavich** [comment]
I've continued supporting astroquery, regions, and astropy.convolution through pull request reviews, issue reporting and tracking, and feature development.  There are no major new developments, but astroquery has continually been refactoring to use more VO-based tools under the hood, which improves long-term maintainability.  The majority of the effort has been in community engagement, while significant effort has gone to basic code maintenance (combating code rot).

**Comment by kelle** [comment]
Hi Adam,  the invoice we received was only for 4,668.42.  Is the plan to invoice for the full award amount of $14,700?

**Comment by keflavich** [comment]
Somehow I missed the notification for this.  Yes, there should be a further invoice, and it should come to close to that amount.

**Comment by jdswinbank** [comment]
Hi @keflavich  — the outstanding invoice for $9,628.62 has now been received. That makes a total of $14297.04, which is pretty close to the expected total. Great!

Could you please (as above) provide a brief summary of the work this invoice covers? Then I will approve it straight away.

**Comment by kelle** [comment]
This work was completed.
