### ISSUE TITLE
Cycle 3 Funding: Starkman & Foreman-Mackey | Units

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#319]
This issue is for tracking the cycle 3 project "Untitled (1)". FR is in https://github.com/astropy/astropy-project/pull/269, and details of the proposal are at https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/Starkman_&_Foreman-Mackey-Units.md . Budget is $8,400 from NASA grant , funded from the NASA grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-nasa)).

**Comment by eteq** [comment]
(FYI,  ``Untitled (1)`` was a bit of a joke FWIW because the original proposal doc doesn't have a title, but I now expect any notebooks produced to have the same title ;)

**Comment by eteq** [comment]
@nstarman - a few details:

1. Can you confirm for us whether the funding for this should go to you as an independent contractor vs your academic institution?  If you're not sure what the answer is and want to discuss it in more detail (or privately) feel free to ping me (and @jdswinbank for #313) on Slack or via email.
2. Can you confirm your preferred email and physical address for this? (and again, feel free to use a private channel if you don't want that publicly visible)

**Comment by jdswinbank** [comment]
Hi @nstarman — bump to the above! We'd love to hear from you regarding independent contractor vs. a subaward to your institution. Please feel free to reply here, or contact us on Slack or at finance@astropy.org.

**Comment by nstarman** [comment]
Thanks for the bump! I've responded on the Astropy slack.

**Comment by AnaGabela** [comment]
[report.pdf](https://github.com/astropy/astropy-project/files/13989367/report.pdf)
Report attached to invoice  [OC#179338](https://opencollective.com/astropy/projects/astropy-nasa/expenses/179338)

**Comment by kelle** [comment]
Accomplishments of this FR are described in the report linked above.
