### ISSUE TITLE
Funding: Infrastructure and core/coordinated package maintenance (Aperio Software)

### ISSUE THREAD

**Issue by eteq** [astropy/astropy-project#320]
This issue is for tracking the cycle 3 project "Infrastructure and core/coordinated package maintenance". FR is in https://github.com/astropy/astropy-project/pull/267, and details of the proposal are at https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/cycle3/Aperio-Infrastructure-Maintenance.md . Budget is $86,400, funded from the Moore grant (please submit invoices [here](https://opencollective.com/astropy/projects/astropy-moore-8435)).

**Comment by astrofrog** [comment]
I'd like to request an extension of this funding until 30th April 2024, which should give plenty of time to bill the remaining hours. Please let me know if you need any information to support this request. Thanks!

**Comment by kelle** [comment]
This is approved.

**Comment by astrofrog** [comment]
We have just submitted an invoice for June 2024 which I believe uses up all the remaining hours on this project (which was carried over to NASA). Would it be possible for someone to confirm? (@astropy/finance-committee) If so, please feel free to close this issue, and we will start billing in future against the Cycle 4 hours.

**Comment by jdswinbank** [comment]
Yes, I can confirm that this closes out this project. Thanks @astrofrog !
