### ISSUE TITLE
olebole should be able to approve astropy PRs

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#327]
### Description

@olebole has a named role in Astropy Team and is a voting member. However, when he approves a PR (e.g., https://github.com/astropy/astropy/pull/14416), it is only a gray check mark, not a green one. What kind of access can/should he get for his role in Astropy?

**Comment by olebole** [comment]
That would be fine with me. Thank you for the trust!

**Comment by hamogu** [comment]
I'll close this issue, since it's dealt with in https://github.com/astropy/astropy.github.com/pull/541
No need to keep both open.
