### ISSUE TITLE
Make a funding request issue template

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#328]
We have some [instructions](https://github.com/astropy/astropy-project/blob/main/finance/process/request-funding.md), but it would be great to have an issue template with off-cycle funding request.

**Comment by pllim** [comment]
I implemented what I think you asked for in 5963e823131ad9d50e022199f7f083d4efc1b63b . You can see them when you select the relevant categories from https://github.com/astropy/astropy-project/issues/new/choose

If you want to update them, feel free to open pull request(s). The templates are stored in https://github.com/astropy/astropy-project/tree/main/.github/ISSUE_TEMPLATE
