### ISSUE TITLE
Need new role: Triage team

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#33]
need Triage Team (or First Responder Team) to recognize the work with Brigitta and Pey Lian do like on issues and PRs. This team could potentially include the new role identified in astropy/coordination#159 to help with making sure first response to issues and PRs is welcoming and timely.

**Comment by pllim** [comment]
This recently was brought up again but ultimately decided it was unnecessary because all core lib contributors can triage (do-ocracy) and other repos in the org have their own teams.
