### ISSUE TITLE
Request for Travel Funding

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#333]
### Full name

Pey Lian Lim

### Description

Attend Scientific Python Developers Summit 2023 on behalf of Astropy. My goal is to see if we can collaborate more closely with other packages in Scientific Python world, especially on the infrastructure side. Please see https://scientific-python.org/summits/developer/2023/ and https://github.com/scientific-python/summit-2023/issues for more details. What you are unwilling to cover, I will claim from Scientific Python, so please let me know.

Do I have to keep meal receipts or not? I don't have to for STScI. I don't remember what I did for the NumFOCUS summit last year. Hope you can clarify. Thanks!

### Total request

USD$2454.90

### Itemized budget

* Flights: USD$860.96
* Hotel: USD$1054.25 (for 5 nights)
* Per diem: USD$434.50 (GSA rate for Seattle)
* Airport parking: USD$72 (for 6 days)
* Gas ($0.655/mile, $17.7 miles each way): USD$23.19
* Light rail between SEA and hotel: USD$10 (estimated)

### Advance needed

Already paid for flights using PEX card (thanks, Kelle!).

**Comment by kelle** [comment]
This was approved on the Moore-Coordination Meetings budget line.  Please submit reimbursement request via [Open Collective to the Moore project](https://opencollective.com/astropy/projects/astropy-moore-8435). 

I checked with NumFocus and unfortunately, they want itemized meal receipts.

**Comment by pllim** [comment]
Claims submitted for $1260.61 .

So including the flights that were paid in advance with PEX card (that I am not claiming from Open Collective), the total expense for this trip was $2121.57. This is a little less than the original estimate because Scientific Python covered a lot of the meals.

Thank you, everyone!
