### ISSUE TITLE
Hire a Finance Admin Assistant

### ISSUE THREAD

**Issue by jdswinbank** [astropy/astropy-project#335]
The Finance Committee thinks we can benefit from an admin assistant.

# Responsibilities

- Attend weekly meetings of the Finance Committee 
- Help with hiring
- Draft job ads, posting them where they should be posted, handling applications, selection rubric, triaging applications, scheduling interviews, selection. 
- Record the process for others to follow in the future.
- Shepard the contract signing workflow between consultants/institutions and NumFocus. 
- Scheduling for finance-related meetings via Google Calendar.
- Assist with purchasing and PEX card reload, balance tracking, and reporting via PEX and Open Collective. 
- Facilitate meetings between Astropy and NumFocus staff, as needed.
- Record processes, workflows, and policies in Google Docs or Markdown files on GitHub.
- Assist with scheduling and drafting community update emails.

# Ideal qualifications

- Familiar with academic culture, ideally astro
- Familiar with software dev culture.
- Experience managing the entire hiring process.
- Experience documenting and communicating processes for general audiences

# Estimated Maximum Budget:

$600/month = $7200/year

We propose to invite Ana Gabela to take up this role on a trial basis.

**Comment by jdswinbank** [comment]
Ana will work for a flat-rate of $600 month, rather than charging per hour. The Finance Committee agree that this is a good approach.

We propose to check in after three months from the start of any contract to see how the work is progressing and if everybody is happy with this arrangement.

**Comment by hamogu** [comment]
I remember writing down a document on how much funding can be approved by the finance committee and at what level Coco participation or community involvement (our internal proposal process) is needed. Unfortunately, I can't find that now - maybe it's a draft that we never merged. 

Anyway, as a matter of process, I think trying out an admin for 3 month is OK, but an annual contract is 7200 $/yr - more than some of the funding proposals the community voted on in the last round. This indicates that it might be better to have a contract of this range put to a vote by the community in the next round instead of just deciding in the finance committee.

**Comment by jdswinbank** [comment]
@pllim:

> Is Ana Gabela from NumFOCUS?

No, but she comes recommended by other folks who have worked with her before.

@hamogu:

> I remember writing down a document on how much funding can be approved by the finance committee and at what level Coco participation or community involvement (our internal proposal process) is needed. Unfortunately, I can't find that now - maybe it's a draft that we never merged.

You are thinking of [APE-19](https://github.com/astropy/astropy-APEs/blob/main/APE19.rst#defining-fundable-activities-and-projects). Specifically:

> Items in the second category — up to $10000 — can be approved by majority vote of the Finance Committee. If, in the judgment of one or more Finance Committee members, the item would not receive widespread support, the Committee will communicate these concerns to the Coordination Committee (CoCo).

In this case, no significant concerns were raised within the Finance Committee. 

That said, I think the story should be a bit more nuanced than just “it follows the letter of the law”, and that's why I insisted on a three-month trial period.

To be explicit, the admin load on the volunteer Finance Committee members has been exceeding the level of time we are able to dedicate to it. Evidence for this is the length of time it's been taken to set up contracts for the Cycle 3 funding, and — in particular — to get started with the open hires funded in the Cycle 3 process. That's a real problem, and I'm hoping that Ana can help us address it. A few months should be enough for us to figure our if this is working or not.

However, it's not obvious that a community vote would actually be helpful here. Most of the projects we get the community to vote on are related to the development and maintenance of the codebase, or closely related projects. Almost all of us have a direct personal involvement with the code: we work on it or use it on a day-to-day basis. Everybody therefore has a well-informed opinion about what needs to be done to make it better.

The same can't be said of the project finances. Most members of the community don't interact with them frequently, and don't have a good day-to-day understanding of what's required to keep them running. Given that, I'm not sure a vote would be particularly meaningful.

**Comment by hamogu** [comment]
That makes sense and I appreciate the extra context in a public forum.

**Comment by pllim** [comment]
Also, if this person is some relative or close friend of decision makers (in this case, one of the Finance Committee members), please declare any conflict of interest. Thanks!

**Comment by pllim** [comment]
p.s. Can't NumFOCUS fill this role for Astropy?

**Comment by kelle** [comment]
- I have been working with Ana in a different capacity but we are not close friends or relatives. 

- No, much experience has shown that NumFOCUS is unable to fill this role.

**Comment by lisamartin72** [comment]
The draft contract for this item has been set up and is attached in the Astropy-Moore ICA Progress Report.

**Comment by AnaGabela** [comment]
Attached you will find the end of year review of my work with the finance committee. After discussing this the committee decided they are happy to continue working together as we have so far. The document has more information of how my time was used. 
[Astropy Year End Review.pdf](https://github.com/astropy/astropy-project/files/14011557/Astropy.Year.End.Review.pdf)
]
