### ISSUE TITLE
Post funded proposals on Ogrants.org

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#337]
From #218 from @hamogu: 
> Suggestion: In addition to having our proposals available for astropy, put them here: https://www.ogrants.org/
> 
> Having them in out github repro or as a link to a google drive (as in https://github.com/astropy/astropy-project/issues/161 for the NASA proposal) might be enough for astropy community members to find them, but contributing them to a more general "open collected proposals" repository for other institutions or projects, who might have less experience with grant writing than our community, to find them. If the PI or finance committee agree, I can do the step of uploading them, but I don't want to do that without agreement, since it's not clear who have the copyright to the proposal. Probably all of us, but certainly the PI, so with their approval, I don't have to waste time on meditating on copyright law (not my preferred past time....)

We can use this issue to discuss and get permissions.

**Comment by eteq** [comment]
As the PI for our NASA grant, I'm all for this, @hamogu! And I think @astrofrog is the PI of the Moore grant, so he's the one to get the permission there.

I initially had misgivings on this in worrying about keeping it up to date, but then after realize the purpose is really to share these to help other people, I realized we don't need to committ to *always* doing this - adding the ones we have now is still useful to others regardless.

**Comment by astrofrog** [comment]
Agree, happy for the Moore one to be posted too!

**Comment by hamogu** [comment]
Done.
