### ISSUE TITLE
Policy for copy editing - push access required

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#34]
From APW:
> We wrote up a policy for copy editing:
>
> When a pull request is feature-complete and has touched the documentation:
Maintainer assesses whether the docs change is “substantial” and requires copy-editing (i.e. single-character changes or fixes generally don’t require copy-editing)
Add “needs-copyedit” label
Request review from @lglattly 
@lglattly reviews pull request:
If a small number of changes required, submit as requested changes
If many changes required, push changes directly to author’s branch
Both of these require a subsequent review from @adrn to verify changes
When copy-editing is complete, @lglattly removes “needs-copyedit” label, adds “copyedited” label 
Copy-editing should not be a long blocker for merging, so if a PR is merged with “needs-copyedit” it can be found later and acted upon (if necessary)
>
> Right now, the point 4.2 "If many changes required, push changes directly to author’s branch" is needed because GitHub can't handle committing a large batch of suggested changes. Also, maintainers can't accept and commit the changes as a batch. However, I believe the only way to enable Lauren push to another users branch would be if we give her write access.
>
> Do you have any ideas or thoughts here?
>
> Thanks!
> - Adrian

**Comment by pllim** [comment]
We do not have a copy editor for a long time. No longer relevant.
