### ISSUE TITLE
Other Request for Funding: Python workshop at AAVSO Annual Meeting 

### ISSUE THREAD

**Issue by mwcraig** [astropy/astropy-project#344]
### Full name

Matt Craig 

### Purpose

This funding will support delivery of a one-day Astropy workshop in conjunction with the 112th Annual Meeting of the American Association of Variable Star Observers (AAVSO). The workshop would be help on Fri, Nov 3 at The Row Hotel, in Somerville, MA, the location of the meeting. There will be a three hour morning session, followed by a lunch break, and a three hour afternoon session.

While the workshop will broadly follow the Astropy workshop delivered at AAS meetings, it will be modified to include more of those parts of the ecosystem relevant for variable star and exoplanet astronomy. The workshop will be delivered by Matt Craig with support from undergraduate research students who attend the meeting.

### Budget

The budget proposed below will limit the per-attendee fee to $50. We anticipate roughly 20 in-person and 20 remote attendees.

| Item | Cost |
| ---- | ----- |
| Room rental | $2,500 |
| AV support, including remote | $1,500 |
| Food | $1,500 |
| Tax | $500 |

### Total request: $6,000

**Comment by jdswinbank** [comment]
The Finance Ctte discussed and approved this request at our meeting of 2023-05-22.

Expenses should be submitted through OpenCollective as part of the (Astropy Moore 8435](https://opencollective.com/astropy/projects/astropy-moore-8435) project. Please let us know if you have any questions!

**Comment by mwcraig** [comment]
Wonderful! I'll work with the AAVSO to get the Astropy logo on the web site for the conference, and with someone there to get them into the OpenCollective system so that they can submit the invoices.

**Comment by mwcraig** [comment]
The workshop was delivered on Nov 3, 2024. I've written a brief summary of the feedback [here](https://docs.google.com/document/d/1Utz77UsMLWmoYYhscWELgTAJufQyzjabaqmf1gmhcf8/edit?usp=sharing), and will talk with the folks leading workshop development about whether they would like me to include a copy of the materials in the `astropy-workshop` repo. The materials as distributed to participants are [here](https://github.com/mwcraig/astropy-workshop/tree/aavso-2023).

The AAVSO has submitted an invoice but please let me know if it hasn't appeared in the system yet.

**Comment by jdswinbank** [comment]
Invoice received (https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/170986).

Thank you for the very nice report! Sounds like a good mix of satisfied participants and a few suggestions for polishing. I think at this point we can close this issue down.
