### ISSUE TITLE
Other Request for Funding: Workshop in Bulgaria

### ISSUE THREAD

**Issue by nden** [astropy/astropy-project#345]
### Full name

Nadia Dencheva

### Purpose

This funding request is for a 5 day Python/Astropy workshop in Sofia, Bulgaria. The workshop will be open to PhD students and astronomers from Bulgaria and the surrounding countries. While Astropy has solid presence in Western Europe, there's not much acceptance of the software in SouthEast Europe. Locally the workshop logistics, announcement and application process will be handled by the Institute of Astronomy, Bulgarian Academy of Sciences. It will be held in [Sofia Tech Park](https://sofiatech.bg/en/) in November, 2023. Exact dates will be confirmed if/when this proposal is funded. Several astropy contributors expressed interest in supporting the workshop.

A tentative schedule for the workshop is

**Day 1**

- Intro and Code of Conduct
- Running Python – environment, ipython, conda, venv, Jupyter notebooks
- Python types
- Functions
- Numpy

**Day 2**

- Intro to Object Oriented Programming
- Scipy – overview
- matplotlib
- Pandas

**Day 3**

- Astropy I/O – FITS and ascii
- Astropy Units, Quantities and Constants
- Coordinates
- Astropy tables

**Day 4**
- Astropy modeling
- FITS WCS
- Ccdproc
- photutils

**Day 5**
- ASDF
- gwcs
- astroplan
- Astropy communities and contribution to astropy

### Budget

The budget below is for 20 people attending in person a 5 day workshop. The budget is in BGN and USD (with the current conversion rate). It does not include travel funds for instructors. The travel assistance is for attendees who need it. 
                    
| item                         | BGN.    | USD |
|-------------------|-------|------ |
| venue                     | 3000  | 1650 | 
| catering                 | 4500  | 2500 |
| hotel, attendees   | 2000 | 1102  | 
| hotel, 5 instructors | 1800  | 1000 |
| travel assistance  | 2000 | 1100  | 
| total                      | 13300 | 7350 |

Edit: (May 24th) Travel Nadia Dencheva: ~$1000.
Edit: (Nov 14th) Travel Aarya Patil: ~320.

**Comment by kelle** [comment]
This request is approved. Please submit expenses to the [Moore budget on Open Collective](https://opencollective.com/astropy/projects/astropy-moore-8435). We also have a PEX card which could be used to pay for things.

We also welcome expenses for instructor travel.

**Comment by nden** [comment]
Thanks! Once we confirm the dates and the instructors (and their location) we'll submit them. 
A typically air ticket from the US is around $1000. I added a note above for my travel expenses.
Some instructors are in Europe.

**Comment by aaryapatil** [comment]
I will be joining as an instructor for this workshop. I would thus like to request a total funding of 320 USD. It would be great if advance reimbursements are possible (I can submit receipts on OpenCollective).

Flight and Rail cost ~270 USD
Local transit/taxi ~50 USD (approximate)

**Comment by jdswinbank** [comment]
@aaryapatil  — we discussed that in the Finance Ctte of 2023-11-20 and agreed, both to support your request for funds, and that we'll approve when you submit receipts (in advance if you have them).

**Comment by eteq** [comment]
@aaryapatil - the finance committee has approved this!  Go ahead and submit on OC when you have it.

**Comment by nden** [comment]
A short summary of the workshop:

The workshop was held in Sofia, Nov 20-24, 2023. Instructors were Aarya Patil, Ivelina Momcheva, James Davies and Nadia Dencheva. There were 20 participants (who were approved and accepted the invitation), however one dropped out in the beginning because of unexpected work assignments.
The workshop schedule and notebooks are in the [workshop repository](https://github.com/nden/astropy_bg_2023). 
The post-workshop survey sent to the participants is [here](https://docs.google.com/forms/d/1KadFUHI4zgTyFsABqBH0_3eY78AZw9FQZ6HVQt9YGS4/edit?pli=1#responses).

We collected feedback at the end of each day which I can share in an email to the finance committee, together with my personal impressions and suggestions for the future. Let me know if I need to share it with anyone else or if you have any questions.

**Comment by kelle** [comment]
This is good enough for Finance, thanks!  You can send the feedback, etc to @BerylKanali , the new community manager.
