### ISSUE TITLE
Create astropy-iers-data repository

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#346]
For https://github.com/astropy/astropy/pull/14819 we need a repository called astropy-iers-data which I think we should just give write access to for the same teams as the core package as it is meant to be used tightly coupled with the core package. The repo can be left empty. Thanks!

**Comment by hamogu** [comment]
Done: https://github.com/astropy/astropy-iers-data

**Comment by astrofrog** [comment]
Thank you!
