### ISSUE TITLE
Request for Funding virtual participation at SciPy 2023

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy-project#351]
### Full name

Derek Homeier

### Purpose

I plan to join the remote part of SciPy 2023; virtual passes are $100.

### Budget

US $ 100.00

**Comment by dhomeier** [comment]
Preferably card; I'll get in touch.

**Comment by eteq** [comment]
Alright, this has been finished and is accounted for so I'm closing the issue.  But  @dhomeier, if you have anything you'd like to share about your time at scipy feel free to leave it right here even after I've closed it!
