### ISSUE TITLE
GH Teams Audit: Delete "affiliated package maintainers"

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#355]
https://github.com/orgs/astropy/teams/affiliated-package-maintainers listing is incomplete, but do we really need to (or want to) keep track of who is what for 47 packages (https://www.astropy.org/affiliated/index.html), or 57 packages if you also count Coordinated.

Let's just delete it. Not sure what is team is for.

**Comment by dhomeier** [comment]
In its current version it is certainly so incomplete (and possibly outdated) that I don't see any possible use in it.

**Comment by pllim** [comment]
@dhomeier , since you are both the Editor and one of CoCo members, I guess your approval is enough?

**Comment by dhomeier** [comment]
I have no background on why those 10 in particular made it onto that list, but unless @eteq has any concerns by tomorrow, I'd say it's ok to remove.

**Comment by pllim** [comment]
Deleted. Thanks!

By the way, Coordinated Packages have their own teams, I think, so this deletion does not affect those teams. And FWIW, I think we should not have a team for packages not in this org (the affiliated).
