### ISSUE TITLE
Support stay for PyData Amsterdam 2023 attendance

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy-project#362]
### Full name

Derek Homeier

### Description

Attending [PyData in Amsterdam](https://amsterdam.pydata.org/program/) to follow up on the NumFOCUS 2023 summit.
Filing this under travel though I am only requesting supplementary funding for extending my stay; travel to/from Amsterdam and conference registration is already covered by NumFOCUS.

### Total request

€ 180.00

### Itemized budget

Lodging: € 143.67 (2 nights @ € 72 / night)
Local transportation: € 36.33 for 3 days

### Advance needed

no

**Comment by kelle** [comment]
This is approved by the Finance Committee. Please submit an reimbursement request, including receipts to the Moore budget: https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/new

**Comment by jdswinbank** [comment]
Expense approved at https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/179682. @dhomeier , if you could please add a brief (**short** paragraph) description of your activities at this meeting, we can close this issue. Thanks!

**Comment by dhomeier** [comment]
Thanks!
I've attended the main sessions as Astropy core team member and supporting NumFOCUS staff who were joining after the Summit. Some notable keynotes to me included facing security vulnerabilities per example of [pickle](https://amsterdam2023.pydata.org/cfp/talk/88HSMQ/), the [scope of ML](https://amsterdam2023.pydata.org/cfp/talk/C778PM/) and a resumé of the preceding NumFOCUS [DISC Unconference](https://numfocus.github.io/disc-unconference-2023-projects/en/intro.html).
