### ISSUE TITLE
Fund participation in AAS 243

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#366]
The 243rd meeting of the American Astronomical Society will be held in-person in New Orleans, USA in Jan 2023.

To further support the goal of increasing Astropy Project visibility at this meeting, we would like to make funding available to offset the travel costs of Project members’ attendance. If you are not fully funded by other sources to attend the meeting, please comment on this issue with a funding request and state the activities you plan to undertake that are beneficial to the Project. The funding request should include items and estimated costs. (For example, “approximately $1000 to cover two nights hotel and half of the airfare.”)

After the meeting, please comment the issue again with any results or take-aways that are useful for the Project as a whole. For example, “I spoke to folks from the AMAZING collaboration about functionality they need and possible new contributions. I got some feedback about the docs of the foobar package and opened issue ## describing the challenge in more detail.”

**Comment by stargaser** [comment]
I would like to ask for partial support for my trip to AAS 243 to support the Astropy workshop. My trip is covered by IRSA but I feel it is justified to ask for some Astropy support.

Requested budget is approximately $600 to cover one night of hotel, baggage fees, and ground transportation.

**Comment by jdswinbank** [comment]
Hi @kelle — the Finance Committee (with you recused) approves this request.

**Comment by eteq** [comment]
@aaryapatil - the committee (sans you, of course) met and approved your request!

**Comment by kelle** [comment]
Everyone should submit expenses to the [Moore budget on Open Collective](https://opencollective.com/astropy/projects/astropy-moore-8435).

**Comment by kelle** [comment]
I've submitted to Open Collective. https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/182431
- I co-facilitated the Astropy Workshop on Sunday...which went swimmingly. Discussed with folks the strategy for next year and how to get the Community Engagement Coordinator more involved.
- I ran a specreduce meet-up. Five people attended and discussed the status of specreduce development and strategies for building momentum and accelerating the rate progress.
- I discussed with other NASA-funded projects the realities of having a cooperative agreement vs a grant.
- I discussed the possibility of an Astropy workshop in ....a South American country which I can't remember right now.

**Comment by aaryapatil** [comment]
Thanks for the ping, @jdswinbank. I do have expenses to claim. Sorry for the delay, I had to figure out what all expenses were covered by my other funding sources. I will submit it this week.

**Comment by aaryapatil** [comment]
I have submitted my expenses to OpenCollective: https://opencollective.com/astropy/projects/astropy-moore-8435/expenses/191344

-  I served as an expert panelist in the "Into the Future: Building on 25 Years of Community Organization in Astro Software Development" Special Session
- Discussed the role of the Astropy finance committee and the governance structure in general, and answered several questions about how other projects can work these structures into their ecosystems
- Discussed a potential 
- Talked about a potential Astropy + LSST workshop with the LSST folks
- Talked a potential Astropy workshop in India!

**Comment by jdswinbank** [comment]
Thanks Aarya!
