### ISSUE TITLE
Request for a new repository (Community Management repository)

### ISSUE THREAD

**Issue by BerylKanali** [astropy/astropy-project#368]
### Description

I am requesting for a new repository as suggested by Moritz. This repository will have all the work and code used in the community management work. This includes community data, engagement tracking scripts, GitHub actions, and output data(which can be later added to the website), survey data and reports that are currently ongoing and any other community work. We have been doing some work on engagement tracking and we have been keeping the work in private repo but we talked about moving it to the Astropy GitHub since we have made good progress.

As the current community manager, I will be responsible for keeping the repository up to date. Here is a link to how the repo will look like, [Astropy community management repo](https://github.com/BerylKanali/community_management) it is currently on my personal account and we have been working on Organizational Mycology's GitHub account as well. [@jduckles](https://github.com/jduckles)  will be helping me set up this new repository and ensuring it has everything we had envisioned. 

cc: @astropy/community-managers, @astropy/coordinators

**Comment by pllim** [comment]
1. Is this requested repo public or private?
2. Our policy recommends we provide access by team, so does that mean you will be added to @astropy/community-managers or something else? @kelle ?

**Comment by BerylKanali** [comment]
@pllim 
1. Ideally it should be public so that the reports we will be updating and plots can be visible to the Astropy community before we figure out how to create a dashboard or add them on the website.
2. > Our policy recommends we provide access by team, so does that mean you will be added to @astropy/community-managers or something else? @kelle ?

@kelle and @eteq can answer this second question.

**Comment by kelle** [comment]
I just updated the membership of the @astropy/community-managers team. So should be good for that team to be assigned the new repo.

**Comment by pllim** [comment]
@kelle , while we're at this, shouldn't the GitHub team membership be consistent with "Community engagement coordinator" names on https://www.astropy.org/team website?

GitHub: astrofrog, eteq, adrn, kelle, eblur, BerylKanali

Website: BerylKanali, mwcraig, kelle, Cadair, eteq

Can I go ahead and clean up the GitHub team?

**Comment by kelle** [comment]
Go for it! Thanks!

**Comment by pllim** [comment]
I see jduckles was invited to the GitHub team but he is not on the website.

**Comment by pllim** [comment]
You could do something similar to https://github.com/orgs/astropy/teams/astroquery-triage where you can add people but only give them Triage access to the repo.

**Comment by pllim** [comment]
I have created a new *public* repo https://github.com/astropy/community_management/ and added the following teams as admin:

* Coordinators
* Community Managers

Please do not post sensitive data there. This would include PIIs and so on.

Since the original request has been satisfied. I am closing this issue. Thanks for your work!
