### ISSUE TITLE
Add @namurphy to Astropy contributor group

### ISSUE THREAD

**Issue by nstarman** [astropy/astropy-project#370]
So I can @ them for reviews.

Ping oh powerful @pllim.

**Comment by pllim** [comment]
I invited @namurphy to the team. It is his decision whether he wants your ping or not. 😆 

For future reference, such request has a template at https://github.com/astropy/astropy-project/blob/main/.github/ISSUE_TEMPLATE/github-admin.yaml

**Comment by nstarman** [comment]
Thanks!
