### ISSUE TITLE
Request for Astropy Coordination Meeting 2024 travel (Utrecht, NL)

### ISSUE THREAD

**Issue by AnaGabela** [astropy/astropy-project#374]
[Coordination Meeting, Utrecht, The Netherlands](https://github.com/astropy/astropy/wiki/SURF-Meeting-2024#2024-astropy-coordination-meeting).  10-14 June 2024. 
 
If you are not fully funded by other sources to attend the meeting, please comment on this issue with a funding request. The funding request should include items and estimated costs. (For example, “approximately $1000 to cover two nights hotel and half of the airfare.”)

**Comment by ceb8** [comment]
Travel funding request for Clara Brasseur (this is the same request that I emailed to the finance committee before this issue was made).

**Total Request:** $1000

**Itemized Budget:**
- Airfare (Edinburgh to Amsterdam): $300
- Train fare (St Andrews to Edinburgh, and Amsterdam to Utrecht): $50
- Hotel (6 nights): $650

**Comment by nden** [comment]
Travel funding request for Nadia Dencheva
55% of trip is funded by STScI. STScI's estimate for the cost is $4000 (in practice it's likely to be less)

**Total request**: $1733

**Itemized budget**:
- Airfair $900 (STScI's total estimate is $2000)
- hotel 6 nights: $430 ( STScI's total estimate is 6 nights * $159: $954)
- per diem: $403 (STScI's total estimate is 8 days * $112: $826)

**Comment by tepickering** [comment]
Travel funding request for Timothy Pickering

Itemized budget:

- Airfare $1320 (YVR-AMS r/t non-stop as of 28/02/24)
- Lodging 5 nights x $159/night GSA max -> $795
- Per diem 5 days x $112/day GSA rate -> $560

Total Request: $2675

**Comment by BerylKanali** [comment]
Travel funding request for Beryl Kanali

- Airfare $1350 (Return ticket Nairobi-Amsterdam)
- Hotel $954 (6 nights * $159)
- Train $25 (Treinkaartjes schiphol->utrecht centraal->schiphol)

**Comment by kelle** [comment]
Travel funding request for Kelle Cruz

Itemized budget:

- Airfare $1500 (JFK-AMS r/t non-stop)
- Lodging 5 nights x $159/night GSA max -> $795
- Per diem 5 days + 2 travel x $112/day GSA rate -> $728
- Ground transport $200
- Total Request: $3200

**Comment by kelle** [comment]
This travel will be supported by NASA funds and so, for those traveling from within the US, you should book on US flag carriers. E.g, Book on Delta even if the flight is operated by KLM.

**Comment by eerovaher** [comment]
Travel funding request for Eero Vaher

Itemized budget:
- Lund-Copenhagen and Copenhagen-Lund train tickets: ~€30
- Copenhagen-Amsterdam and Amsterdam-Copenhagen bus tickets: €143.49
- Amsterdam-Utrecht and Utrecht-Amsterdam train tickets: ~€30
- Hotel in Utrecht (4 nights):  €652,03
TOTAL: ~€860

**Comment by aaryapatil** [comment]
Travel funding request for Aarya Patil

Itemized budget:

Train $200
Lodging 5 nights x $159/night GSA max -> $795
Per diem 5 days + 2 travel x $112/day GSA rate -> $560
Total Request: $1555

**Comment by neutrinoceros** [comment]
Travel funding request for Clément Robert.

Itemized budget
- Train ~$500
- Hotel (5 nights) ~$800
**Total Request: $1300**

**Comment by jdswinbank** [comment]
Hi @neutrinoceros , @aaryapatil , @eerovaher , @kelle , @tepickering — these requests are all approved by the Finance Committee.

**Comment by dhomeier** [comment]
I have not finalised my travel dates, so this may be reduced to 5 nights, but filing here for a 6 nights' stay (9-15 June):

Itemised budget:

- Train ca. 160-180€ -> $200 
- Accommodation 6 nights x $152/night (est.) -> $912
- Per diem 6 days x $112/day GSA rate -> $672

**Total Request: $1784**

**Comment by jdswinbank** [comment]
@dhomeier — your request is approved. Sorry for the late response!

**Comment by dhomeier** [comment]
Thanks, and sorry for not following procedure (in particular not sending a notification by email) – should have followed our own FR link! ;-)

**Comment by neutrinoceros** [comment]
I realized that I forgot to include the city tax from my hotel reservation and meals... my actual expenses amount to $1800 ($1,798.30 to be precise), which is $500 over budget compared to what was approved for.
Can I still ask for reimbursement for all of it (if not, it's okay, that's completely on me !) ?
Regardless, who should I be speaking to to get my money back ? Thanks !

**Comment by pllim** [comment]
> who should I be speaking to to get my money back ?

Should be the Finance Committee, I think. Or at least they would know who to point you to.

**Comment by jdswinbank** [comment]
Hi @neutrinoceros — please go ahead and submit a reimbursement claim for the full amount (~$1800). I think it's likely the Finance Committee will approve it (but I can't guarantee that until I've talked to the others); if we have any questions, we'll get back to you.

**Comment by jdswinbank** [comment]
Requests to settle before we can close this:

- [ ] @nden 
- [ ] @aaryapatil 
- [ ] @ceb8 
- [ ] @tepickering 
- [ ] @eerovaher 
- [ ] @neutrinoceros 
- [ ] @dhomeier

**Comment by neutrinoceros** [comment]
@jdswinbank thank you. Request submitted at https://opencollective.com/astropy/projects/astropy-nasa/expenses/208227

**Comment by pllim** [comment]
Are everything in order here? When can we close this issue? Thanks!

**Comment by jdswinbank** [comment]
I don't immediately see a record of claims from @eerovaher or @dhomeier . Did I miss them?

**Comment by dhomeier** [comment]
No, at least not mine – was not sure if this was connected to setting up the Opencollective account, but anyway wanted to initiate that first – sorry for the delay!

**Comment by eerovaher** [comment]
I had managed to forget about this, but I have submitted a claim now: https://opencollective.com/astropy/projects/astropy-nasa/expenses/213626

**Comment by dhomeier** [comment]
Linked my claim above
