### ISSUE TITLE
Consider 📌 pinning `astropy-project` repo to `astropy` org main page

### ISSUE THREAD

**Issue by jduckles** [astropy/astropy-project#388]
### Description

I frequently come to https://github.com/astropy looking for the astropy-project repo to look through issues there. It would be nice if it was one of the series of pinned repositories as its used so much for project activities. 

There is a nice free spot among the five currently pinned repos, a mockup of what it would sort-of look like: 
![image](https://github.com/astropy/astropy-project/assets/119403/53d32d11-47b8-478d-bd8b-1f43b62b7951)

**Comment by pllim** [comment]
I didn't even know you can pin them. Thanks! I replaced the defunct `package-template` with `astropy-project`.
