### ISSUE TITLE
Request for Travel Funding to SPIE Astronomical Telescopes & Instrumentation 2024

### ISSUE THREAD

**Issue by tepickering** [astropy/astropy-project#398]
### Full name

Timothy Pickering

### Description

The abstract for [Specreduce: An AstroPy-affiliated Toolbox for Spectroscopic Data Reduction](https://spie.org/astronomical-telescopes-instrumentation/presentation/Specreduce-An-AstroPy-affiliated-Toolbox-for-Spectroscopic-Data-Reduction/13101-27) was accepted as an oral presentation. It is listed as 13101-27 on the schedule at [https://spie.org/as24/conferencedetails/astronomy-control-software](https://spie.org/as24/conferencedetails/astronomy-control-software). Specreduce is an `astropy`-coordinated package and exposure at this very large SPIE meeting in the context of other presentations on data reduction pipelines would be a great way to help foster greater communication and collaboration within the community.

### Total request

USD ~~$4119~~ $3250

### Itemized budget

- Lodging: 6 nights at $205/night -> ~~$1230~~ $546 actual
- Meals: 6 days at $129/day -> $774
- Airfare: ~~$1200 r/t AMS-NRT~~ $1015 AMS-HND actual
- Local Transport: $65 (9500 yen r/t via train)
- Registration: $850

Lodging and Meals rates based on 2024 GSA/State Department per diem allowances. Airfare is quoted out of AMS because I presume to be at the `astropy` Coordination Meeting the week immediately preceding the SPIE.

### Advance needed

Ideally, I would like to receive reimbursement for the significant costs of registration and airfare soon after they are incurred, previous to the meeting. This would equate to an advance of USD $2050.

**Comment by tepickering** [comment]
i should add, slots for oral presentations are oversubscribed so we did very well to be awarded one. it would not reflect well on us to withdraw at this point.

the actual lodging costs are looking to be much less than the GSA rate. i have a quote for $546. airfare has gone down as well and i have a quote for $1015 AMS-HND.

**Comment by tepickering** [comment]
we are close enough to the travel dates that i won't be needing a travel advance.

**Comment by tepickering** [comment]
i edited my budget above. the registration deadline is at the end of this week, may 31. if i need to find other support to cover that, please let me know ASAP. it might be possible...

**Comment by kelle** [comment]
Thank you for your patience!  Even though this is quite a large request, the finance committee has approved it.  (This situation is also a useful test case to help us modify and improve our process.)

I will get in touch with you via Slack DM to discuss payment and reimbursement options.
