### ISSUE TITLE
Astronomical Data Science Workshops

### ISSUE THREAD

**Issue by ivastar** [astropy/astropy-project#402]
### Project Team

The team requesting the funding consists of members of the Advisory Committee for the Carpentries [Astronomical Data Science curriculum](https://datacarpentry.org/astronomy-python/). This group has been meeting semi-annually for the last 2 years in order to oversee the development of these materials. All of these members are at the intersection of the Carpentries community, open-source astronomy community, and the astronomical data science community. Most of the committee members are trained Carpentries instructors and have delivered workshops using these materials at different venues including the AAS meetings.

The members of the Advisory Committee currently are:

- **Azalee Bostroem** ( @abostroem ) is an LSST-DA Catalyst fellow at University of Arizona and has been an instructor with the Carpentries since 2012.  She was a co-PI on the APS venture partnership grant which funded the development of this curriculum, led the development effort, and served as a lesson maintainer for its first year as an official Carpentries Curriculum. She is now the chair of the curriculum advisory committee and organizes and instructs workshops, including at AAS meetings. She will help organize the workshops in this proposal and instruct as needed.
- **Ivelina Momcheva** (@ivastar) is a head of the Data Science Group at MPIA. She has been a certified Carpentries instructor since 2017 and has delivered tens of workshops on computational skills for scientists including a week-long Astropy workshop in Sofia, Bulgaria in 2023. She organized a pilot workshop for the Astronomical Data Science Curriculum at STScI in 2021 and was lead instructor at the winter 2023 AAS meeting workshop. She will help organize the workshops in this proposal.
- **Adam Hughes** (tautme) is an astronomer turned data scientist. He has been an instructor at the winter and summer 2022 AAS meeting and a pilot workshop at STScI. He is a potential instructor for the workshops in this proposal.
- **Meredith Rawls** ( mrawls ) is a Research Scientist at the University of Washington who works for Vera C. Rubin Observatory. She develops and validates open-source software and data pipelines for Rubin's upcoming Legacy Survey of Space and Time. She became a certified Carpentries Instructor in 2017, has helped several organizations put on successful software and data science workshops and bootcamps, led an eScience Data Science for Social Good summer project in 2022, and is a tireless advocate for open data in her increasingly urgent work on satellite constellation interference mitigation. She has served as a helper at the first pilot workshop of this curriculum and as an instructor at the Winter 2022 AAS meeting.  She is a potential instructor for the workshops in this proposal.
- **Heather Andrews Mancilla** is the secretary of the curriculum advisory committee and helped organize a pilot workshop at the eScience center in Delft. She will help organize the workshops in this proposal.

Additional support: the curriculum lesson maintainers are also potential instructors for these workshops.
- **Rodolfo Montez** (rudyphd) was co-PI of the APS grant that funded this curriculum and part of the team that guided its development. He was an instructor at the first pilot workshop.
- **Ralf Kotulla** (rkotulla) has instructed at the winter 2023 and 2024 AAS workshops. 

### Purpose

In this proposal we request funding to carry out two workshops within the next 12 months at conferences which bring together minority researchers. The events we are targeting are:

- [2024 NDISTEM Conference](https://www.sacnas.org/conference) organized by SACNAS, Oct 31st - Nov 2nd in Phoenix, AZ
- [NSBP and National Society of Hispanic Physicists 2024 Annual Conference](https://nsbp.org/events/EventDetails.aspx?id=1837931) in Houston, TX, November 13-17, 2024

Our Astronomical Data Science Workshops aim to empower undergraduate students, early-career researchers, and educators in astronomy with critical data science skills, focusing on the Foundations of Astronomical Data Science curriculum. This curriculum is designed to equip learners with the abilities to handle large astronomical datasets, perform advanced database operations such as SQL queries, joins, and filtering, and produce publication-quality data visualizations. Over approximately 10 hours, participants will delve into software packages widely used in data science, including Pandas for data management, Astropy for astronomy-specific tasks, and Astroquery for accessing remote databases.

The hands-on curriculum leverages two major astronomical datasets: the Gaia satellite's billion-star catalog and the Pan-STARRS photometric survey. These resources allow participants to engage directly with real-world astronomical phenomena, such as the GD-1 stellar stream—a globular cluster stretched into an arc by the Milky Way's gravitational forces. Through a guided exploration, participants will reproduce parts of a significant analysis on GD-1, learning to identify and visualize this stream while gaining insights into the mass of the Milky Way and the intriguing gaps within the stream caused by dark matter interactions.

The workshop emphasizes practical skills like crafting complex queries, managing data with Pandas DataFrames and Astropy Tables, and customizing detailed plots. Furthermore, it introduces best practices in creating reproducible workflows and transforming coordinates between common systems, enhancing both the efficiency and impact of astronomical research. This initiative aligns closely with the goals of the Astropy project, promising to enrich the astronomical community's capabilities in data science and open new avenues for discovery and analysis.

The proposed workshops, held at events for minority researchers and utilizing open-source curriculum to teach data science skills, actively work to reduce the systemic barriers to entry into the data science field and astronomical research. By providing high-quality, accessible educational opportunities, we aim to empower underrepresented groups with the skills needed to excel in data science and astronomical research with the large surveys coming online in the next few years. At its core, the Carpentries value diversity, inclusivity, access, community, and empowering everyone to build knowledge. Carpentries instructors are trained to use evidence-based techniques to create an inclusive classroom. Supporting this initiative would demonstrate a committed effort to support the professional growth and representation of minority researchers in astronomical data science.

The Astronomical Data Science curriculum is designed to integrate core Astropy packages — such as coordinates, units, and Tables — within the context of an astronomical workflow. It also includes in-depth use cases of affiliated packages such as astroquery and gala. At the end of Day 1, we will include a session to introduce the Astropy project, discussing how participants can engage with and contribute to the community through various channels, fostering a collaborative and inclusive environment for scientific advancement. By introducing Astropy and its affiliated packages through these workshops, we aim to attract contributors and users from underrepresented groups, thereby enriching the Astropy project with a wider range of insights and experiences. 

### Project / Work

Our project encompasses the organization and execution of two comprehensive 2-day workshops, each designed to accommodate approximately up to 50 participants. 

The team required is 2 instructors and 2 helpers. 

Instructors need to know the curriculum in detail in order to be able to teach it. The instructors will be recruited from the team above. 
2 instructors are needed because 10 hours of content is too much to be delivered by a single instructor. 

Helpers are needed to assist the participants in solving problems through-out the workshop and especially during hands-on exercises. Helpers are usually recruited locally from the city where the event is, either from local astronomy departments or the local Carpentries community. We propose to incentivize the helpers' participation by covering their conference registration.

### Budget

Overall organization will be done by the team on our own time. We plan to hold two workshops. For each workshop we assume 50 participants, two instructors, and two helpers. We assume instructors will require airfare, three nights hotel, and M&I, while helpers are assumed to be local. The events we are targeting are in Phoenix, AZ and Houston, TX. The two metropolitan areas are equally well connected via flights and have similar hotel and convention center pricing. Registration fees for the two events are also similar. Therefore we do not provide separate budgets for each event, but use overall figures based on experiences from bringing these workshops to the Winter AAS meetings. For each workshop, we request  support for:

- Travel and lodging: $2000 per instructor ($4000 total)
- Conference registration:
    * $725 (professional registration for instructors; $1450 total)
    * $450 (student registration for helpers; $900 total)
- Venue (incl. A/V support): $1650
- Refreshments: $20/person/day ($2000 total)

Total per workshop: $10,000 

Currency: US $
TOTAL (2 workshops): 20,000

### Period of Performance

The period of performance is 1 year.

**Comment by aaryapatil** [comment]
@ivastar Could you open this as a PR instead, similar to the other Cycle 4 funding proposals?

**Comment by ivastar** [comment]
Moved this to a PR: https://github.com/astropy/astropy-project/pull/403
