### ISSUE TITLE
Issue with Zenodo webhook for core package

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#416]
### Description

It looks like the Zenodo webhook didn't work when I did the astropy 6.1.0 release on GitHub as per core package release instructions:

_Upload the release to Zenodo by creating a GitHub Release off the GitHub tag. Click on the tag in [astropy/astropy](https://github.com/astropy/astropy/tags) and then click on “Create release from tag” on the upper right. The release title is the same as the tag. In the description, you can copy and paste a description from the previous release, as it should be a one-liner that points to CHANGES.rst. When you are ready, click “Publish release” (the green button on bottom left). A webhook to Zenodo will be activated and the release will appear under https://doi.org/10.5281/zenodo.4670728 . If you encounter problems during this step, please contact the Astropy Coordination Committee._

As per the last sentence, this is a request for the coordination committee to investigate why this isn't working. @eteq - I think you've looked into this in the past?

**Comment by pllim** [comment]
I dunno why but Zenodo likes to randomly turn off the auto hook thingy on their end. Multiple times now for different packages, I have to go back to turn it back on over at Zenodo and then resend the release hook. I did it for v6.1

https://zenodo.org/records/11121433
