### ISSUE TITLE
Request for Supplemental Travel Funding to present Astropy at PyData Prague OSSci Meetup

### ISSUE THREAD

**Issue by dhomeier** [astropy/astropy-project#417]
### Full name

Derek Homeier

### Description

On invitation from OSSci Prague I am giving a talk at [PyData Prague #20](https://pydata.cz/#open-source-science--pydata-prague-20-1652024-at-fnspe-ctu) on our governance structure.
The organisers are covering travel and one night of accommodation, as the meeting takes place in the late afternoon/evening.
I am asking for additional funding to cover one night before the meeting, since train connections are making it difficult to get there on the same day, and two days' per-diem.

### Total request

142.28 €

### Itemized budget

- Lodging: 1/3 nights € at 54.56 €/night -> 54.56 €
- Meals on and after workshop day and during travel: 84 € 
- Local transportation: 3 x 30 ČKr for tram -> 3.70 €

### Advance needed

no

**Comment by dhomeier** [comment]
updated the budget to actual expenses after reimbursements from OSSci

**Comment by jdswinbank** [comment]
Sorry for the delay in getting back to this. Approved by Finance Committee vote.

**Comment by kelle** [comment]
Has this been sorted? Can this be closed?

**Comment by dhomeier** [comment]
submitted to https://opencollective.com/astropy/projects/astropy-nasa/expenses/218105
Sorry for the delay with getting the receipts together!

**Comment by dhomeier** [comment]
Thanks!
