### ISSUE TITLE
Invoice for AAS 243 Astropy Workshop

### ISSUE THREAD

**Issue by bmorris3** [astropy/astropy-project#425]
### Full name

Brett Morris

### Purpose

The Astropy workshop at the 243 AAS meeting in New Orleans overshot the budget because I underestimated the AV costs when I ordered catering. This is my fault. The remaining balance to be paid is $1,929.99. 

Attached are the invoice and card authorization forms:
* [Invoice: STScI - 001693.pdf](https://github.com/astropy/astropy-project/files/15337353/STScI.-.001693.pdf)
* [AAS Credit Card Authorization](https://github.com/astropy/astropy-project/files/15337352/AAS.Credit.Card.Authorization.pdf)

### Budget

USD $1,929.99

**Comment by kelle** [comment]
Finance committee approved this. I will use our Expensify card to pay.

**Comment by AnaGabela** [comment]
Just sent the cc authorization from to pay this. CC Finance and Brett.
