### ISSUE TITLE
10k citation action items

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#431]
Should thank our users and ask them to join in as contributors.

1. @Cadair offered to put a banner on Astropy docs.
2. Encourage institutions that provided support (see Institutional Support at the bottom of https://www.astropy.org/credits.html) to do press releases (@eteq @adrn @crawfordsm @taldcroft @cmarmo @arlissc and please ping anyone I missed here)

**Comment by kelle** [comment]
We could also ask Moore and NASA if they were interested in doing some press.  @crawfordsm ?

**Comment by kelle** [comment]
Has anyone asked the communications person at NumFocus? I can do that if noone else has.

**Comment by crawfordsm** [comment]
Please send me an email and I can start the conversations on the NASA side.  It's unlikely to raise to the level of NASA press release, but at the very least, we can likely highlight it as an Open Science success story.

**Comment by kelle** [comment]
To add a little bit more context, one of the astropy papers (I don't actually know which one) is closing in on reaching 10,000 citations.  This is a "big deal" and apparently there are very few astro papers that have reached this milestone. Maybe @adrn can provide more inspiration and details for the copy of any press release.

**Comment by adrn** [comment]
The [first astropy paper](https://ui.adsabs.harvard.edu/abs/2013A%26A...558A..33A/abstract)! I can draft something and circulate for our various institution press offices to look at.

**Comment by pllim** [comment]
> Has anyone asked the communications person at NumFocus?

I don't think so (but I am also not very active there). @kelle , please go ahead. Thanks!

**Comment by kelbylorenz** [comment]
Hi! I'm Kelby, the Digital Marketing Specialist at NumFOCUS. This is so exciting! What are you looking to get help with from the NF side? Would you like us to write a release for you all to share? Or do you need help amplifying? I'm happy to help, but I just want to get a grasp on what you need. Congrats on this accomplishment!

**Comment by jdswinbank** [comment]
> This is a "big deal" and apparently there are very few astro papers that have reached this milestone.

If you [believe ADS](https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=database%3Aastronomy&q=property%3Arefereed&sort=citation_count%20desc%2C%20bibcode%20desc&p_=0), the Astropy paper is the thirteenth most cited in their collection of peer-reviewed astronomy articles, just slightly above [Stephen Hawking](https://ui.adsabs.harvard.edu/abs/1975CMaPh..43..199H/abstract).

**Comment by kelbylorenz** [comment]
Happy to help! If you all wouldn't mind putting together a bullet list of the important info you want to highlight, I can draft something for you all to look over! Thank you!

**Comment by adrn** [comment]
@kelbylorenz Sorry for the delay! 
Others: [feel free to add to this list](https://docs.google.com/document/d/1p_L1zu8QCDhIQZg5zgsyT9hBvUyLkYUxJSuSswLgtSs/edit#heading=h.f27pbv5564tu) — anyone on astropy-core-maintainers should have edit access.

**Comment by astrofrog** [comment]
Has anyone figured out when we are predicted to pass 10k citations? 😊

**Comment by keflavich** [comment]
to get the relevant data....
```python
citing_papers = ads.SearchQuery(q="citations(bibcode:2013A&A...558A..33A)", rows=10000, fl=['citation_count', 'author', 'year', 'id', 'bibcode', 'pubdate'], max_pages=100)
dates = [art.pubdate for art in tqdm.tqdm(citing_papers)]

# hacky
dates_arr = np.array([x.replace('00', '01') for x in dates], dtype='datetime64[D]')
```
(note that many pubs lack month-of-publication)

We're at 9976 as of now, and the latest rate is ~1900/yr (though climbing).  So, roughly 5 days?  We're probably at it now, but ADS doesn't update entirely automatically, iirc.

**Comment by astrofrog** [comment]
Looks like we've now indeed passed 10k according to ADS!

**Comment by pllim** [comment]
So... what do we do now? I mean, we just got another award, so would be nice to throw this in too while fire is hot.

**Comment by adrn** [comment]
I was waiting for @kelbylorenz to draft something, but I could draft a press release instead -- I'll do it over the weekend and ping here.

**Comment by adrn** [comment]
OK actually I had 12 minutes right now, so I drafted a press release in the same google doc as above: [here](https://docs.google.com/document/d/1p_L1zu8QCDhIQZg5zgsyT9hBvUyLkYUxJSuSswLgtSs/edit)

This is sort of written from the perspective of the project, but we might want it to be third person instead. I could hand it to our communications team for editing and feedback, if others agree. Since we crossed 10,000 a few days ago, this is mildly time sensitive (thanks @astrofrog and @pllim for noticing :)) @astropy/coordinators

**Comment by pllim** [comment]
Thanks, @adrn ! CoCo not meeting for another 2 weeks but I have alerted them of this.

**Comment by kelle** [comment]
That text looks great to me!  I've added a couple small comments.

**Comment by pllim** [comment]
NumFOCUS press release is out: https://numfocus.medium.com/astropy-paper-reaches-10-000-citations-276421fa8681

I am putting it on the website: https://github.com/astropy/astropy.github.com/pull/630

We done here? Thanks, all!
