### ISSUE TITLE
Proposal to add @svank as a reproject maintainer

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#435]
Following the process described [here](https://github.com/astropy/astropy-project/blob/main/policies/adding-new-role-members.md) I would like to propose adding Sam Van Kooten (@svank) as a reproject maintainer. Sam has contributed a significant sub-module (reproject.adaptive) as well as other significant improvements and has the skills and understanding of the code and process to become a maintainer for the coordinated package.

Is it correct that the CoCo will handle the process from this point onwards as described in the policy? Let me know if there is anything I can do to help.

@svank - could you confirm that you would still be happy to be a co-maintainer? (I think Stuart or I chatted with you about this a while back)

**Comment by astrofrog** [comment]
Maintainers of coordinated packages have roles on the team page, and as such I believe they follow the same process as core. The idea of having them be coordinated packages is precisely that their management is overseen by the project.

**Comment by astrofrog** [comment]
The policy at https://github.com/astropy/astropy-project/blob/main/policies/adding-new-role-members.md does not specifically mention the core package, it is a policy for all roles.

**Comment by pllim** [comment]
Okay then. CoCo will meet on 2024-07-22.

**Comment by pllim** [comment]
> I believe they follow the same process as core

If only we could speak for maintenance as well... But that is a battle for another day.

**Comment by astrofrog** [comment]
An additional point to raise with the CoCo is whether the policy could be relaxed so that it is not the CoCo that is responsible for the whole process of filling roles - that is, perhaps any existing role holder could propose someone to hold a role and start the whole 2 week process etc.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/issues/435#issuecomment-2239194529

Might go faster if you open a PR with proposed change and CoCo can discuss on Monday.

**Comment by astrofrog** [comment]
@pllim - done in https://github.com/astropy/astropy.github.com/pull/611

**Comment by pllim** [comment]
Oh, I mean proposal to *update the policy*. 😅

**Comment by astrofrog** [comment]
Oh I see, will do

**Comment by astrofrog** [comment]
Hmm actually I'm not really sure about changing it, I'll leave it to the CoCo to think about how they would like to handle this.

**Comment by pllim** [comment]
> I'm not really sure about changing it

What do you mean? Does your request at https://github.com/astropy/astropy-project/issues/435#issuecomment-2239194529 still stand or you have a different request now?

**Comment by svank** [comment]
> @svank - could you confirm that you would still be happy to be a co-maintainer? (I think Stuart or I chatted with you about this a while back)

Yes, I'm still happy to do it (though as I've never been a maintainer before, we should probably have an orientation chat at some point)

**Comment by pllim** [comment]
Whatever you chat about, please take high-level notes, @astrofrog and/or @svank , because I think we need a real maintainer onboarding guide!

**Comment by pllim** [comment]
Re: onboarding -- Coincidentally, I dug up this old issue that's still open. 😬 https://github.com/astropy/astropy-project/issues/158

**Comment by pllim** [comment]
Congrats and welcome to the team!
