### ISSUE TITLE
Communicate with Moore potential budget changes

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#60]
Moore budget is all "Consultants" and has no line item for fringe ("benefits"). Since we anticipate paying some folks (via subawards) with summer salary, we are anticipating incurring fringe costs. Please confirm with Moore that this is an ok re-budget.

**Comment by jdswinbank** [comment]
I think this is done, right? Or, at least, it has not been an issue in the last ~year. Can we close it? (It'd be great if we actually had an artefact from Moore or NumFOCUS providing the confirmation requested, of course...)
