### ISSUE TITLE
Maintainer Contract: Matt Craig

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#63]
The Interim Finance Committee and the CoCo are working on getting Matt Craig on contract (a subaward to MSU) to work on conda packaging, package template, and Learn Astropy. The full Scope of Work will be posted once it has been finalized.

**Comment by jdswinbank** [comment]
An agreement was entered into between Astropy/NumFOCUS and the Minnesota State University covering the period 1 July 2020 through 1 July 2021. The agreed scope of work is described in the attached PDF.

- [July 2020 — Craig — SOW.pdf](https://github.com/astropy/astropy-project/files/5464484/July.2020.Craig.SOW.pdf)

**Comment by kelle** [comment]
Finance committee approved re-allocation of unspent funds to Spring 2022 teaching buyout.

**Comment by pllim** [comment]
Is this still relevant? Last update was 3 years ago.
