### ISSUE TITLE
[WIP] Rotating Project Managers group

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#69]
[not fully flushed out idea]
A rotating "traffic cop" whose job it is to make sure project-wide issues move along and don't fall through the cracks. The idea is that one person would really have their head in the astropy-game for ~1 month and could plan their schedule appropriately ahead of time. Probably rotate through the CoCo at first but this role could be expanded to include other maintainers....and would serve as very useful training for being on the CoCo.

**Comment by pllim** [comment]
Like a... project manager?

**Comment by bsipocz** [comment]
let's not call it "traffic cop"?

**Comment by kelle** [comment]
- I guess project manager, but not thinking about anything long term, just shepherding things along. 
- I agree that traiffic cop is not great. Other name suggestions would be great. How about Shepard?

**Comment by bsipocz** [comment]
"project manager" can be a rotating role, too, assuming the close project community knows it's rotating, and whoever is actually in the role is the person doing it, but that same issue comes up independently how we call it.

It would be just like we rotate moderators on telecons. Inventing secondary meaning to ordinary words is generally confusing, I feel it's better to find the one that is widely used for similar roles elsewhere, and add an extra adjective if we must.

**Comment by pllim** [comment]
"Termed project manager" then? I am just thinking in terms of what will motivate people to take on this role. One of the factor will be how appealing the title will appear on their resumes. "Traffic cop" is not a standard industry term in software and will have little appeal, IMHO.

**Comment by bsipocz** [comment]
and I'm also thinking in terms that others recognize, not just for the CV. 
E-mails like "Hey, I'm the current astropy traffic cop taking up the task to deal with this xy issue" reads super bad. If this is a prerequisite role for CoCo, then come the naming should be according to that in seriousness.

**Comment by kelle** [comment]
Termed makes me think that the role is 1-2 years long. How about "Rotating Project Manager"?

**Comment by bsipocz** [comment]
That sounds good to me, as does "on duty PM". It also could be a group role, "project managers" with some communication/transparency that who is actually on duty. The same would be nice for the CoCo tbh, as in many times it's not clear whether an issue got picked up behind the scenes or fallen through the cracks.

**Comment by pllim** [comment]
"acting", "active", or your "rotating" works for me. 👍

**Comment by pllim** [comment]
Superseded by the COTR stuff.
