### ISSUE TITLE
Maintainer Contract: Adam Ginsburg

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#70]
The interim finance committee is working on getting a contract for Adam Ginsburg (as a subaward to his institution) for his work on spectroscopy packages, astroquery, and astropy.convolution. The full Scope of Work will be posted once it has been finalized.

**Comment by jdswinbank** [comment]
An agreement was entered into between Astropy/NumFOCUS and the University of Florida covering the period 1 June 2020 through 1 June 2021. The agreed scope of work is described in the attached PDF.

- [June 2020 — Ginsburg — SOW.pdf](https://github.com/astropy/astropy-project/files/5464426/June.2020.Ginsburg.SOW.pdf)

**Comment by kelle** [comment]
This contract is complete and funds were allocated.
