### ISSUE TITLE
Hire a person to help with PRs, especially first time contributions

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#75]
We can hire a person to help improving the contribution process.
- respond to new PRs within 24 hours
- help with technical hoops (e.g., rebase, squash, tests, etc)
- work on establishing and/or polishing guidelines for contribution process

**Comment by kelle** [comment]
The job ad is in #65 and we're currently accepting applications.

**Comment by pllim** [comment]
24 hours might be too tight of a deadline. How about 2 business days?

**Comment by bsipocz** [comment]
24hrs turnaround is a 🤖, and for PRs the bot is in fact responds that quickly, and with the labeling done, the ball is with the maintainers already...

**Comment by kelle** [comment]
Search is underway. If I recall correctly, the search committee is @crawfordsm , @eteq , @eblur , and @pllim. Please correct me if that's incorrect.

**Comment by pllim** [comment]
Search for [2020_githubresponder.rst](https://github.com/astropy/project/blob/master/finance/jobs/2020_githubresponder.rst), yes.

**Comment by pllim** [comment]
Hiring decision has been made. Is the Project going to send out an official announcement to the community and close this out?

**Comment by jdswinbank** [comment]
For the record, official announcements were eventually made to astropy-dev:

- https://groups.google.com/g/astropy-dev/c/qlNMpLpnPXI
- https://groups.google.com/g/astropy-dev/c/-TLLC0S4UOY

**Comment by jdswinbank** [comment]
An agreement was entered into between Astropy/NumFOCUS and Madison Bray covering the period 1 August 2020 through 31 July 2021. The agreed scope of work is described in the attached PDF.

- [August 2020 — Bray — SOW.pdf](https://github.com/astropy/astropy-project/files/5464494/August.2020.Bray.SOW.pdf)

**Comment by pllim** [comment]
I don't think this is relevant anymore?
