### ISSUE TITLE
astropy.cosmology needs maintainers

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#77]

**Comment by pllim** [comment]
I think it needs a lead and deputy.

**Comment by bsipocz** [comment]
can't edit the issue, but indeed, cosmology needs a maintainer or two

**Comment by bsipocz** [comment]
(and I thought we got rid of the lead-deputy distinction)

**Comment by kelle** [comment]
Yes, we did. These are issues that I moved from the private coordinators repo this morning. Notice the date is from 2017.

**Comment by pllim** [comment]
Weird, the team page still has lead/deputy.

**Comment by astrofrog** [comment]
We decided to do it, but haven't done it yet :) There is a bit of a backlog going from decisions -> actions due to lack of time!

**Comment by adrn** [comment]
We have Nathaniel in this role now - can this be closed?
