### ISSUE TITLE
Invoicing workflow

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#79]
Currently, independent contractors have to upload PDF invoices via Rocket in order to get paid. NumFocus (Leah & Lynn) will work on either making an invoice template, or better yet, a form on Rocket which folks can use to submit the info rather than making an actual invoice.

**Comment by kelle** [comment]
@lisamartin72 , Do you have any thoughts on this?

**Comment by lisamartin72** [comment]
I have a template that I can place in your team drive for now. Let me look at a way to add it to Rocket.

**Comment by kelle** [comment]
Contractors were provided an invoice template and this seems to be working just fine.
