### ISSUE TITLE
Move GSOC money to SunPy

### ISSUE THREAD

**Issue by kelle** [astropy/astropy-project#84]
Since we have the Moore money now, we discussed it with Stuart and it makes sense to move the GSOC money (from Open Astronomy) into the SunPy account. 

I don't think we need to take any action, but FYI.

**Comment by kelle** [comment]
@Cadair As far as you know, did this get taken care of?

**Comment by Cadair** [comment]
I think so, let me double check.

**Comment by dpshelio** [comment]
@kelle not all it's done. We are still missing few things:
 - Last year GSoC money to SunPy and other smaller groups
 - If we want SunPy to keep the accounting for all OA, then there's also more to transfer.

I'll give you details via e-mail.

**Comment by kelle** [comment]
@dpshelio , can this be closed? (I'll open a new issue for the request you sent this morning via email.)

**Comment by bsipocz** [comment]
My latest update on this that the money was still with astropy. Has this been changed in the last few weeks?

**Comment by hamogu** [comment]
@kelle: Did NumFOCUS tell us that the money has been moved. If not, can you decide to reopen instead of continuously closing and re-opening?

**Comment by hamogu** [comment]
Or just keep both. It's annoying that, as far as we know, NumFOCUS has not been able to do that years after. We've definitely requested that more than once.

**Comment by kelle** [comment]
I chatted with Lynn about this and she's going to work on it and report progress back to our email thread (subject: "Astropy / Sunpy & Open Astronomy GSOC money")

**Comment by jdswinbank** [comment]
Mail from NumFOCUS Finance of 2021-07-06, subject “Re: Astropy / Sunpy & Open Astronomy GSOC money”, seems to confirm that this issue has been resolved. That was sent to stakeholders from both projects, and nobody has objected. I therefore propose to close this issue. Please reopen if you feel this matter has not been satisfactorily resolved.
