### ISSUE TITLE
Go through ADASS BoF document and make sure we extract all actionable item

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-project#85]
I can do this, but this is just a reminder to do so, and others are welcome to help:

https://docs.google.com/document/d/1nbnE5CiQhhG43cd1Kq6IfHiUSuVxf8O8-HnD1fWJTxM/edit#

**Comment by pllim** [comment]
Wow from 2016...

**Comment by kelle** [comment]
If you think everything has been filed away and this issue can be closed, please say so. I didn't want to close the issue and lose some good ideas.

**Comment by pllim** [comment]
I don't think I was in that ADASS? So, I'll have to defer to others.

**Comment by kelle** [comment]
Attendance is not necessary to move forward on this issue. If you look at the document, you can see the ideas -- many of them are excellent and could potentially still be relevant. It's just a question if any of those still need to be turned into issues someplace or if they have been "absorbed" into the project already. You could also comment directly on the doc.

**Comment by pllim** [comment]
Ah, okay. I'll have a look when I get the chance.

**Comment by pllim** [comment]
Update: I added notes/edits where I can.
