### ISSUE TITLE
Affiliated package review guideline: Change orange badge to yellow

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#92]
In `project/affiliated/affiliated_package_review_guidelines.md`, orange should really be yellow. Traffic light has yellow, not orange. Also, orange it too close to red.

**Comment by astrofrog** [comment]
In the UK the lights are amber not yellow! ;) But I agree yellow could provide better contrast.

**Comment by hamogu** [comment]
I always thought that orange played on the astropy logo as an aspirational color.

**Comment by Cadair** [comment]
It's very likely that white text on yellow will have very poor contrast on screen, which is bad for accessibility. This is currently also the case with the green background from shields.io as well.

**Comment by pllim** [comment]
Text color can be changed to blue on yellow or whatever. There is no rule saying that text color needs to be the same in all the badges.

**Comment by taldcroft** [comment]
If we are serious about accessibility then red / green is one of the first color combos to avoid. But we do have words there so not the end of the world.  One accessible color palette that came up from a quick google is:

![image](https://user-images.githubusercontent.com/348089/81711983-294ebd80-9442-11ea-86bb-7536c26d8b37.png)

**Comment by Cadair** [comment]
My concern was less people being able to distinguish the different colours (because as you say there are words) as it is people being able to read the words because of the lack of contrast.

For the record: https://github.com/sunpy/sunpy.org/issues/227

**Comment by hamogu** [comment]
We are at risk of getting to the bike-shedding stage here. If there are arguments either way and no consensus to change, I suggest we just leave everything as it is. What matters is the sequence not good enough / acceptable / great and the current color scheme can convey that.

**Comment by taldcroft** [comment]
I'm fine with yellow with blue text. I was just thinking that as long as we are in there changing colors, that this is an opportunity to make this high-profile page more accessible to color blind people.  My former colleague was in this boat and had to deal with this a lot.

**Comment by pllim** [comment]
Superseded by #334
